<!doctype html>
<html lang="en" ng-app="GiadaAdmin">
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
    
	<script src="http://ajax.googleapis.com/ajax/libs/angularjs/1.2.15/angular.min.js"></script>
	<script src="http://ajax.googleapis.com/ajax/libs/angularjs/1.2.15/angular-route.min.js"></script>
	<script src="{{ url('public/admin-angular/app/scripts/app.js') }}" type="text/javascript"></script>
	<script src="{{ url('public/admin-angular/app/scripts/controllers/newsList.js') }}" type="text/javascript"></script>
	<script src="{{ url('public/admin-angular/app/scripts/controllers/login.js') }}" type="text/javascript"></script>
	<script src="{{ url('public/admin-angular/app/scripts/controllers/newsAdd.js') }}" type="text/javascript"></script>
	<script src="{{ url('public/admin-angular/app/scripts/controllers/newsEdit.js') }}" type="text/javascript"></script>
	<script src="{{ url('public/admin-angular/app/scripts/controllers/logout.js') }}" type="text/javascript"></script>
	<script src="{{ url('public/admin-angular/app/scripts/controllers/version.js') }}" type="text/javascript"></script>
	<script src="{{ url('public/admin-angular/app/scripts/services/api.js') }}" type="text/javascript"></script>
	<script src="{{ url('public/admin-angular/app/scripts/services/user.js') }}" type="text/javascript"></script>
	<script src="{{ url('public/admin-angular/app/scripts/filters/date.js') }}" type="text/javascript"></script>
	<script src="{{ url('public/admin-angular/app/scripts/utils.js') }}" type="text/javascript"></script>
	
	<link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css">
	<link rel="stylesheet" href="{{ url('public/admin-angular/app/styles/global.css') }}">

	<!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
	<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
	<!--[if lt IE 9]>
		<script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
		<script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
	<![endif]-->
</head>

<body>
	
	<div class="container-fluid">
		
		<div class="row">
			
			<div class="col-md-12">
				<h1 ng-controller="versionController">Giada Admin {[{ version }]}</h1>
			</div>
		</div>
		
		<div ng-view></div>
	
	</div>
</body>
</html>
