<div class="container">

	<div class="row margin-top-xl">
		<div class="col-md-12 text-center">
			<h1>Old versions.</h1>
		</div>
	</div>
	
	<div class="row margin-top-xl">
		<div class="col-md-10 col-md-offset-1">
			<table class="table">
				<tr>
					<th>version</th>
					<th>filename</th>
					<th>date</th>
					<th>OS</th>
				</tr>
				{% for f in files %}
				<tr>
					<td>{{ f['version'] }}</td>
					<td><a href="{{ url('download/grab/') }}{{ f['dl'] }}/{{ f['version'] }}">{{ f['fname'] }}</a></td>
					<td>{{ f['date'] }}</td>
					<td>{{ f['os'] }}</td>
				</tr>				
				{% endfor %}
			</table>
		</div>
	</div>

</div>
