{% extends 'base.phtml' %}

{% block title %}Press - {% endblock %}

{% block description %}, press{% endblock %}

{% block keywords %}, press{% endblock %}

{% block metas %}{% endblock %}

{% block styles %}{% endblock %}

{% block scripts %}{% endblock %}

{% block content %}
<div class="container">

	<div class="row margin-top-xl">
		<div class="col-md-12 text-center">
			<h1>Spread the word.</h1>
		</div>
	</div>

	<div id="documentation" class="row margin-top-xl">
		<div class="col-md-10 col-md-offset-1">
			<p>Giada is a free, minimal, hardcore audio tool for DJs, live performers and electronic musicians. How does it work? Just pick up your channel, fill it with samples or MIDI events and start the show by using this tiny piece of software as a loop machine, drum machine, sequencer, live sampler or yet as a plugin/effect host. Giada aims to be a compact and portable virtual device for Linux, Mac OS X and Windows for production use and live sets.</p>

      <p>Carefully crafted by the almighty Monocasual Laboratories, Giada provides several workflows that make it a container of multiple devices. A sample player, where sounds and beats are triggered on the fly; a traditional loop machine, powered by multiple channels; a song composer, thanks to the action-oriented approach and the action editor; a live sampler or yet a plugin processor/host, with VST support and MIDI I/O routing.</p>

      <p>Giada is actively developed on GitHub where many friends/collaborators push changes and suggest ideas, as well as on the official forum (for non-techies). It's also available in the main Linux distributions' repositories like Debian, Ubuntu, Arch Linux and many more. Free for use and distribution under the GPL v3 license. 100% palm oil and gluten free.</p>

			<h2>Press review</h2>
			<ul>
				<li><p>Linux Magazine - <a href="http://www.linux-magazine.com/Online/Features/Processing-Loops-and-More-with-Giada">Processing Loops and More with Giada</a></p></li>
				<li><p>MusicRadar, December 26, 2015 - <a href="http://www.musicradar.com/tuition/tech/20-great-free-and-open-source-music-making-programs-582934">20 great free and open source music making programs</a></p></li>
				<li><p>Libre Music Production, April 7, 2015 - <a href="http://libremusicproduction.com/articles/lmp-asks-7-interview-giovanni-zuliani">LMP Asks #7: An interview with Giovanni A. Zuliani [member of Monocasual Laboratories]</a></p></li>
			</ul>

			<h2>Artworks</h2>
			<ul>
				<li><p><a href="{{ url('public/img/press/giada-logotype.svg') }}">Giada logotype, SVG</a></p></li>
				<li><p><a href="{{ url('public/img/press/giada-logo.svg') }}">Giada logo, SVG</a></p></li>
				<li><p><a href="{{ url('public/img/press/giada-screenshot.png') }}">Reference screenshot, PNG</a></p></li>
			</ul>

			<h2>Social profiles</h2>
			<ul>
				<li><p><a href="https://github.com/monocasual/giada">Giada on GitHub</a></p></li>
				<li><p><a href="https://www.facebook.com/GiadaYourHardcoreLoopmachine">Giada on Facebook</a></p></li>
				<li><p><a href="https://giadamusic.com/img/social-icons-youtube.png">Giada on YouTube</a></p></li>
				<li><p><a href="http://giadaloopmachine.tumblr.com/">Giada on Tumblr</a></p></li>
				<li><p><a href="https://twitter.com/GiadaLooper">Giada on Twitter</a></p></li>
				<li><p><a href="https://plus.google.com/103544024553691934077/posts">Giada on Google+</a></p></li>
			</ul>

			<h2>Contacts</h2>
			<p>Please contact us at <a href="mailto:giadaloopmachine@gmail.com">giadaloopmachine@gmail.com</a> for information, interviews, additional press kits.</p>
		</div>
	</div>

</div><!-- container -->
{% endblock %}
