{% extends 'base.phtml' %}

{% block title %}Docs - {% endblock %}

{% block description %}, documentation{% endblock %}

{% block keywords %}, documentation{% endblock %}

{% block metas %}{% endblock %}

{% block styles %}{% endblock %}

{% block scripts %}{% endblock %}

{% block content %}
<div class="container">

	<div class="row margin-top-xl">
		<div class="col-md-12 text-center">
			<h1>The path of knowledge.</h1>
		</div>
	</div>

	<div id="documentation" class="row">
		<div class="col-md-12">
			{{ content() }}
		</div>
	</div>

</div>
{% endblock %}
