{% extends 'base.phtml' %}

{% block title %}Screenshots - {% endblock %}

{% block description %}, screenshots{% endblock %}

{% block keywords %}, screenshots{% endblock %}

{% block metas %}{% endblock %}

{% block styles %}{% endblock %}

{% block scripts %}{% endblock %}

{% block content %}
<div class="container">

	<div id="documentation" class="row">
		<div class="col-md-9">
			{{ content() }}
		</div>
		<div id="side-menu" class="col-md-3 margin-top-xl">
			<div>{{ partial('partials/docs/documentation-side-menu') }}</div>
		</div>
	</div>

</div>
{% endblock %}
