{% extends 'base.phtml' %}

{% block title %}Source - {% endblock %}

{% block description %}, source{% endblock %}

{% block keywords %}, source{% endblock %}

{% block metas %}{% endblock %}

{% block styles %}{% endblock %}

{% block scripts %}{% endblock %}

{% block content %}
<div class="container">

	<div class="row margin-top-xl">
		<div class="col-md-12">
			<h1 class="text-center">Return to the source of it all.</h1>
			<h2 class="margin-top-xl description">We are very proud of our source code! Giada is written in a mixture of C and C++ and is made up of ~100 files, ~30,000 lines, plus several other external libraries.</h2>
		</div>
	</div>

	<div class="row margin-top-xl">
		<div class="col-md-12">
			<table class="table">
				<tr>
					<th>name</th>
					<th>size (kB)</th>
					<th>sha</th>
				</tr>
				{% for d in dir %}
					{% if d['path'] in blacklist %}
						{% continue %}
					{% endif %}
					<tr>
						<td><a href="{{ url('source/show/' ~ d['path']) }}">{{ d['name'] }}</a></td>
						{% if d['type'] == 'file' %}
							<td>{{ d['size'] }}</td>
						{% else %}
							<td>directory</td>
						{% endif %}
						<td>{{ d['sha'] }}</td>
					</tr>
				{% endfor %}
			</table>
		</div>
	</div>

</div>
{% endblock %}
