{% extends 'base.phtml' %}

{% block title %}{{ file }} - Source - {% endblock %}

{% block description %}, source, {{ file }}{% endblock %}

{% block keywords %}, source, {{ file }}{% endblock %}

{% block metas %}{% endblock %}

{% block styles %}{% endblock %}

{% block scripts %}{% endblock %}

{% block content %}
<div class="container">

	<div class="row margin-top-xl">
		<div class="col-md-12">

			{% if type == 'dir' %}

			<h1>{{ path }}</h1>
			<table class="table margin-top-l">
				<tr>
					<th>name</th>
					<th>size (kB)</th>
					<th>sha</th>
				</tr>
				{% for d in dir %}
				<tr>
					<td><a href="{{ url('source/show/' ~ d['path']) }}">{{ d['name'] }}</a></td>
					{% if d['type'] == 'file' %}
						<td>{{ d['size'] }}</td>
					{% else %}
						<td>directory</td>
					{% endif %}
					<td>{{ d['sha'] }}</td>
				</tr>
				{% endfor %}
			</table>

			{% else %}

			<h1>{{ file }} - source code</h1>
			<pre class="code margin-top-l"><code>{{ content }}</code></pre>

			<h2>Informations</h2>
			<p>total size: {{ size }} kB - <a href="{{ html_url }}" title="{{ file }} on GitHub/Giada">see it on GitHub</a></p>

			<h3>Commits</h3>
			<table class="table">
				<tr>
					<th>date</th>
					<th>author</th>
					<th>message</th>
				</tr>
				{% for c in commits %}
				<tr>
					<td>{{ c['commit']['committer']['date'] }}</td>
					<td>{{ c['commit']['committer']['name'] }}</td>
					<td>{{ c['commit']['message'] }}</td>
				</tr>
				{% endfor %}
			</table>

			{% endif %}

		</div>
	</div>

</div>
{% endblock %}
