{% extends 'base.phtml' %}

{% block title %}Features - {% endblock %}

{% block description %}, features{% endblock %}

{% block keywords %}, features{% endblock %}

{% block metas %}{% endblock %}

{% block styles %}{% endblock %}

{% block scripts %}{% endblock %}

{% block content %}
<div class="container">

	<div class="row margin-top-xl">
		<div class="col-md-12 text-center">
			<h1>A list of astonishing features.</h1>
		</div>
	</div>

	<div class="row">
		<div class="col-md-10 col-md-offset-1">
      <div class="feature left">
        <img src="{{ url('img/icon-cog.png') }}" alt="*">
        <h2 class="margin-top-xl description">Ultra-lightweight internal design</h2>
        <p>Giada is designed to be a fast and reliable audio tool, focused on productivity. Super-sleek interface and 100% exotic dependencies free. Based on few external libraries, you can save it into a floppy disk.</p>
      </div>

      <div class="feature right">
        <img src="{{ url('img/icon-grid.png') }}" alt="*">
        <h2 class="margin-top-xl description">32 bit floating point sample-accurate audio engine</h2>
        <p>All samples are internally converted and managed to provide hi-definition audio mixing, with ALSA, JACK, CoreAudio, ASIO and DirectSound full support. Thanks to its precise sample-based calculations, Giada can run for hours without losing a bpm.</p>
      </div>

      <div class="feature left">
        <img src="{{ url('img/icon-sheets.png') }}" alt="*">
        <h2 class="margin-top-xl description">Multi-thread/multi-core support</h2>
        <p>The audio stuff runs in a separate process, while the interface is at your command. In this way the music never stops, even during the heaviest processing.</p>
      </div>

      <div class="feature right">
        <img src="{{ url('img/icon-mixer.png') }}" alt="*">
        <h2 class="margin-top-xl description">Unlimited number of channels with different playback modes and combinations</h2>
        <p>Manage loops and events; play samples; mute and stop channels; launch single-shot samples with a key press; compose your song with layered loops, actions or takes from the external world. Use Giada as a live drum machine or yet process live any input and redirect it to the speakers: everything through your computer's keyboard.</p>
      </div>

			<div class="feature left">
				<img src="{{ url('img/icon-note.png') }}" alt="*">
				<h2 class="margin-top-xl description">MIDI I/O, VST/VSTi plugin support</h2>
				<p>Control Giada through your favorite hardware devices, or let it drive any other thing (physical or logical) that can read MIDI messages, with support for custom <a href="https://github.com/monocasual/giada-midimaps">MIDI lightning messages</a>. Use all of your favorite VST effects and VST instruments, transforming Giada into a native VST host, also suitable for live processing. Plugin support for Linux, Windows and OSX, of course.</p>
			</div>

			<div class="feature right">
				<img src="{{ url('img/icon-edit.png') }}" alt="*">
				<h2 class="margin-top-xl description">Live sampler from external inputs, built-in wave editor</h2>
				<p>Record samples from the real world with automatic channel selection and input delay compensation. Then cut, trim, silence, normalize and pitch your takes via the minimal yet very tasty integrated editor. The core engine is powered by Libsamplerate, providing a state-of-the-art resampling quality.</p>
			</div>

			<div class="feature left">
				<img src="{{ url('img/icon-remote.png') }}" alt="*">
				<h2 class="margin-top-xl description">Action recorder + action editor + live quantizer = total control</h2>
				<p>Record live your performance or craft it carefully via the action editor, possibly building the structure of the song from scratch. Finally, align the samples on exact fractions of beats to gain an ultra-precise live performance, thanks to the integrated live quantizer.</p>
			</div>

			<div class="feature right">
				<img src="{{ url('img/icon-db.png') }}" alt="*">
				<h2 class="margin-top-xl description">Patch-based system with support for all major uncompressed file formats</h2>
				<p>Giada handles any uncompressed audio format, such as .wav, .aiff and many others. All your sounds and actions can be safely stored into small and compact open source files.</p>
			</div>

      <div class="feature left">
        <img src="{{ url('img/icon-heart-big.png') }}" alt="*">
        <h2 class="margin-top-xl description">100% open-source GPL stuff, in a constant stage of development</h2>
        <p>Giada keeps growing every day, free for use and distribution: you can use it without any limitations. Help us to improve it more! Feel free to submit your ideas or any bug found to our <a href="http://www.giadamusic.com/forum">forum</a>, or join us on <a href="https://github.com/monocasual/giada">GitHub</a>.</p>
      </div>
		</div>
	</div>

</div><!-- container -->
{% endblock %}
