{% extends 'base.phtml' %}

{% block title %}Features - {% endblock %}

{% block description %}, features{% endblock %}

{% block keywords %}, features{% endblock %}

{% block metas %}{% endblock %}

{% block styles %}{% endblock %}

{% block scripts %}{% endblock %}

{% block content %}
<div class="container">

	<div class="row margin-top-xl">
		<div class="col-md-12 text-center">
			<h1>A list of astonishing features.</h1>
		</div>
	</div>

	<div class="row">
		<div class="col-md-10 col-md-offset-1">
			<h2 class="margin-top-xl description">Ultra-lightweight internal design</h2>
			<p>Giada is designed to be a fast and reliable audio tool, focused on productivity. 100% exotic dependencies free. Based on few external libraries, you can save it into a floppy disk.</p>

			<h2 class="margin-top-xl description">Multi-thread/multi-core support</h2>
			<p>The audio stuff runs in a separate process, while the interface is at your command. In this way the music never stops, even during the heaviest processing.</p>

			<h2 class="margin-top-xl description">32 bit floating point audio engine</h2>
			<p>All samples are internally converted and managed to provide hi-definition audio mixing, with ALSA, JACK, CoreAudio, ASIO and DirectSound full support.</p>

			<h2 class="margin-top-xl description">Unlimited number of audio channels controlled via computer keyboard</h2>
			<p>Manage loops and events, play samples, mute and stop channels: everything through your computer's keyboard.</p>

			<h2 class="margin-top-xl description">Different playback modes and combinations</h2>
			<p>Launch single-shot samples with a key press; compose your song with layered loops, actions or takes from the external world; use Giada as a live drum machine or yet process live any input and redirect it to the speakers.</p>

			<h2 class="margin-top-xl description">Bpm and beat sync with sample-accurate loop engine</h2>
			<p>Giada can run for hours without losing a bpm, thanks to its sample-based calculations.</p>

			<h2 class="margin-top-xl description">MIDI input and output support</h2>
			<p>Control Giada through your favorite hardware devices, or let it drive any other thing (physical or logical) that can read MIDI messages.</p>

			<h2 class="margin-top-xl description">Built-in wave editor</h2>
			<p>Cut, trim, silence, normalize and pitch your sample via the minimal yet very tasty integrated editor.</p>

			<h2 class="margin-top-xl description">VST and VSTi plugin support</h2>
			<p>A feature which transforms Giada into a native VST host, also suitable for live processing. Plugin support for Linux, Windows and OSX, of course.</p>

			<h2 class="margin-top-xl description">Live sampler from external inputs</h2>
			<p>Record samples from the real world with automatic channel selection and input delay compensation. </p>

			<h2 class="margin-top-xl description">Live quantizer</h2>
			<p>Align the samples on exact fractions of beats to gain an ultra-precise live performance.</p>

			<h2 class="margin-top-xl description">Action recorder + action editor</h2>
			<p>Record live your performance or craft it carefully via the action editor, possibly building the structure of the song from scratch.</p>

			<h2 class="margin-top-xl description">Patch-based system</h2>
			<p>All your sounds and actions can be safely stored into small and compact open source files.</p>

			<h2 class="margin-top-xl description">Support for all major uncompressed file formats</h2>
			<p>Giada handles any uncompressed audio format, such as .wav, .aiff and many others.</p>

			<h2 class="margin-top-xl description">A constant stage of development</h2>
			<p> Giada keeps growing every day. Feel free to submit your ideas or any bug found to our <a href="http://www.giadamusic.com/forum">forum</a>, or join us on <a href="https://github.com/monocasual/giada">GitHub</a>.</p>

			<h2 class="margin-top-xl description">100% open-source GPL stuff</h2>
			<p>Giada is free for use and distribution: you can use it without any limitations. Help us to improve it more!</p>
		</div>
	</div>

</div><!-- container -->
{% endblock %}
