{% extends 'base.phtml' %}

{% block title %}{% endblock %}

{% block description %}{% endblock %}

{% block keywords %}{% endblock %}

{% block metas %}
{# fb opengraph #}
<meta property="og:title" content="{{ config.metas.title }}" />
<meta property="og:type" content="website" />
<meta property="og:image" content="{{ config.urls.base }}{{ url(config.metas.image) }}" />
<meta property="og:url" content="{{ config.urls.base }}" />
<meta property="og:description" content="{{ config.metas.description }}" />
<meta property="fb:admins" content="100001854661538" />
{# twitter #}
<meta name="twitter:card" content="summary" />
<meta name="twitter:url" content="{{ config.urls.base }}" />
<meta name="twitter:title" content="{{ config.metas.title }}" />
<meta name="twitter:description" content="{{ config.metas.description }}" />
<meta name="twitter:image" content="{{ config.metas.image }}" />
{% endblock %}

{% block styles %}{% endblock %}

{% block scripts %}{% endblock %}

{% block content %}
<div class="container">

	<div class="row margin-top-xl">
		<div class="col-md-12">
			<h1 class="text-center">Your hardcore loop machine.</h1>
			<h2 class="margin-top-xl description">{{ config.metas.description }}</h2>
			<h4 class="text-center"><a class="see-it-in-action" href="http://www.youtube.com/user/GiadaLoopMachine" target="_blank">see it in action!</a></h4>
		</div>
	</div>

	<div class="row margin-top-xl">
		<div class="col-md-10 col-md-offset-1">
			<div  id="index-carousel" class="carousel slide" data-ride="carousel">

				<!-- Indicators -->
				<ol class="carousel-indicators">
					<li data-target="#index-carousel" data-slide-to="0" class="active"></li>
					<li data-target="#index-carousel" data-slide-to="1"></li>
				</ol>

				<!-- Wrapper for slides -->
				<div class="carousel-inner">
					<div class="item active">
						<a href="{{ url('screenshots') }}" title="More screenshots!">
							<img src="{{ url('img/screenshots/giada-loop-machine-screenshot-14-carousel.jpg') }}" alt="Giada Loop Machine 0.9.0">
						</a>
					</div>
					<div class="item">
						<a href="{{ url('screenshots') }}" title="More screenshots!">
							<img src="{{ url('img/screenshots/giada-loop-machine-screenshot-15-carousel.jpg') }}" alt="Giada Loop Machine 0.9.0">
						</a>
					</div>
					<div class="item">
						<a href="{{ url('screenshots') }}" title="More screenshots!">
							<img src="{{ url('img/screenshots/giada-loop-machine-screenshot-16-carousel.jpg') }}" alt="Giada Loop Machine 0.9.0 full screen">
						</a>
					</div>
				</div>

				<!-- Controls -->
				<a class="left carousel-control" href="#index-carousel" role="button" data-slide="prev">
					<span class="glyphicon glyphicon-chevron-left"></span>
				</a>
				<a class="right carousel-control" href="#index-carousel" role="button" data-slide="next">
					<span class="glyphicon glyphicon-chevron-right"></span>
				</a>

			</div>
		</div>
	</div>


	<div class="row center-block margin-top-xl">
		<div class="col-md-6">
			<h3><img alt="*" src="{{ url('img/icon-box.svg') }}" class="margin-right-s">Lightweight and powerful</h3>
			<p>32 bit floating point audio engine, sample-accurate looping system, multithread support, super-sleek interface. 100% exotic dependencies free.</p>
		</div>

		<div class="col-md-6">
			<h3><img alt="*" src="{{ url('img/icon-knob.svg') }}" class="margin-right-s">Lots of useful tools</h3>
			<p>Tweak your sounds with the live sampler from external sources, the live quantizer, a built-in wave editor, the action recorder and the action editor.</p>
		</div>
	</div>


	<div class="row center-block">
		<div class="col-md-6">
			<h3><img alt="*" src="{{ url('img/icon-sine.svg') }}" class="margin-right-s">VST and MIDI support</h3>
			<p>Giada can load VST and VST instruments, as well as read/write MIDI messages from/to any device out there, both hardware and software.</p>
		</div>

		<div class="col-md-6">
			<h3><img alt="*" src="{{ url('img/icon-heart.svg') }}" class="margin-right-s">100% open-source GPL</h3>
			<p>Giada is constantly under development, free for use and distribution: you can use it without any limitations. Help us to improve it more!</p>
		</div>
	</div>

	<div class="quotes row margin-top-xl">
    <div class="col-md-6 col-md-offset-3">
      <p><i>“This software is f*cking awesome.”</i> ― Cinderskull27</p>
      <p><i>“Giada is one of the best open platform audio tool out there.”</i> ― blinkworth1</p>
      <p><i>“Discovering Giada has completely changed my life.”</i> ― D1RTY J0E</p>
    </div>
  </div>

	<div class="row margin-top-xl">
		<div class="col-md-12">
			<a href="{{ url('download') }}">
			<input type="button" class="download-btn btn btn-default center-block" value="Download it!">
			</a>
			<div class="text-center margin-top-s">
        latest version: {{ config.changelog.version }} |
        <a href="{{ url('documentation') }}">docs</a> |
        <a href="https://github.com/monocasual/giada" title="Giada @ Git Hub">fork it on GitHub</a> |
        <div class="paypal-inline">{{ partial('partials/socials/paypal') }}</div>
      </div>
		</div>
	</div>

	<div class="row">
		<div class="col-md-10 col-md-offset-1">
			<h2 class="margin-top-xl text-center">Sharing is caring!</h2>
			<div class="list-inline text-center margin-top-xl">
				{{ partial('partials/socials/facebook-like') }}
				{{ partial('partials/socials/twitter-like') }}
				{{ partial('partials/socials/reddit') }}
				{{ partial('partials/socials/flattr') }}
				{{ partial('partials/socials/google-plus') }}
				{{ partial('partials/socials/github') }}
			</div>
		</div>
	</div>
</div><!-- container -->

<div class="container-fluid news-list">
  <div class="row">
      <div class="col-sm-12">
				<div class="container">
					<div class="row">
						<div class="col-md-10 col-md-offset-1">
							<h2 class="margin-top-xl text-center">Latest news from our laboratories.</h2>
							{% for n in news %}
							<div class="margin-top-l padding-top-s {% if !loop.first %} line-top {% endif %}">
								<h3 class="description">{{ n.getTitle() }}</h3>
								<span class="pull-left margin-right-s red">{{ n.getDate() }} ― </span> {{ n.getText() }}
							</div>
							{% endfor %}
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
{% endblock %}
