{% extends 'base.phtml' %}

{% block title %}404 - {% endblock %}

{% block description %}, 404{% endblock %}

{% block keywords %}, 404{% endblock %}

{% block metas %}{% endblock %}

{% block styles %}{% endblock %}

{% block scripts %}{% endblock %}

{% block content %}
<div class="container">
	<div class="row margin-top-xl">
		<div class="col-md-8 col-md-offset-2">
			<h1 class="text-center">404: such an epic fail.</h1>
			<div class="margin-top-xl">
				<p>We are very sorry, this page does not exist. But you always could:</p>
				<ul>
					<li>return to the <a href="{{ url('') }}">index page</a></li>
					<li>download the amazing <a href="{{ url('download') }}">latest version</a></li>
					<li>explore our <a href="{{ url('forum') }}">official forum</a></li>
					<li>fork the project on <a href="https://github.com/monocasual/giada">GitHub</a></li>
				</ul>
			</div>
		</div>
	</div>
</div>
{% endblock %}
