<div id="footer" class="container">

	<div class="row border-top padding-top-s">
		<div class="col-md-8">
			<p class="text">Giada is developed by<br>
				<a href="http://www.monocasual.com" title="Monocasual" class="imagelink">
					<img src="{{ url('img/monocasual-logo-mini.png') }}" alt="monocasual" />
				</a>
			</p>
		</div>

		<div class="col-md-4">
			<p class="text">VST Plug-In Technology by Steinberg.<br>
			VST is a trademark of Steinberg Media Technologies GmbH.</p>
		</div>
	</div>

	<div class="row margin-top-xl">
		<div class="col-md-8 col-md-offset-2">
			<div class="text-center social-links">
				<a href="http://sourceforge.net/projects/giada-looper" title="Giada @ Source Forge" class="imagelink">
					<img src="{{ url('img/social-icons-sourceforge.png') }}" alt="source forge" title="Giada @ Source Forge">
				</a>
				<a href="{{ url('feed') }}" title="Giada RSS feed" class="imagelink">
					<img src="{{ url('img/social-icons-rss.png') }}" alt="RSS" title="Giada RSS feed">
				</a>
				<a href="https://www.facebook.com/GiadaYourHardcoreLoopmachine" title="Giada @ Facebook" class="imagelink">
					<img src="{{ url('img/social-icons-facebook.png') }}" alt="Facebook" title="Giada @ Facebook">
				</a>
				<a href="http://giadaloopmachine.tumblr.com" title="Giada @ Tumblr" class="imagelink">
					<img src="{{ url('img/social-icons-tumblr.png') }}" alt="tumblr" title="Giada @ Tumblr">
				</a>
				<a href="https://twitter.com/GiadaLooper" title="Giada @ Twitter" class="imagelink">
					<img src="{{ url('img/social-icons-twitter.png') }}" alt="twitter" title="Giada @ Twitter">
				</a>
				<a href="https://github.com/monocasual/giada" title="Giada @ Git Hub" class="imagelink">
					<img src="{{ url('img/social-icons-github.png') }}" alt="git hub" title="Giada @ Git Hub">
				</a>
				<a href="http://www.youtube.com/user/GiadaLoopMachine" title="Giada @ Youtube" class="imagelink">
					<img src="{{ url('img/social-icons-youtube.png') }}" alt="youtube" title="Giada @ Youtube">
				</a>
				<a href="https://plus.google.com/103544024553691934077/posts" title="Giada @ Google+" class="imagelink">
					<img src="{{ url('img/social-icons-google.png') }}" alt="Google+" title="Giada @ Google+">
				</a>
				<a href="http://www.kvraudio.com/product/giada-by-monocasual" title="Giada @ KVR Audio" class="imagelink">
					<img src="{{ url('img/social-icons-kvr.png') }}" alt="kvr audio" title="Giada @ KVR Audio">
				</a>
			</div>
		</div>
	</div>

	<div class="row margin-top-xl">
		<div class="col-md-12 text-center">
			<p class="text links">
				<a href="{{ url('news-archive') }}">news archive</a> |
				<a href="{{ url('source') }}">source code</a> |
				<a href="{{ url('privacy') }}">privacy policy</a> |
				<a href="{{ url('tos') }}">terms of service</a> |
				<a href="{{ url('cookies') }}">cookies</a> |
				<a href="mailto:{{ config.urls.email }}">contact us</a>
			</p>
		</div>
	</div>
</div><!-- footer -->
