<div class="container">
	
	<div class="row border-top padding-top-s" id="footer">
		<div class="col-md-8">
			<p class="text">Giada is developed by<br>
				<a href="http://www.monocasual.com" title="Monocasual" class="imagelink">
					<img src="{{ url('public/img/monocasual-logo-mini.png') }}" alt="monocasual" />
				</a>
			</p>

			<p class="text links">
				<a href="{{ url('news-archive') }}">news archive</a> |
				<a href="{{ url('privacy') }}">privacy policy</a> |
				<a href="{{ url('tos') }}">terms of service</a> |
				<a href="mailto:{{ config.urls.email }}">contact us</a>
			</p></div><div class="col-md-4">
			<p class="text">VST Plug-In Technology by Steinberg.<br>
			VST is a trademark of Steinberg Media Technologies GmbH.</p>
		</div>
		<div class="deluge-clear"></div>
	</div>
	
</div>
