<div class="container">

	<div class="row border-btm padding-btm-s" id="header">
		<div class="col-md-3 logo margin-top-s">
			<a href="{{ url('') }}" title="Giada - Your Hardcore Loopmachine" class="imagelink">
				<img class="space-none" src="{{ url('public/img/giada-logo-small.png') }}" alt="Giada - Your Hardcore Loopmachine">
			</a>
		</div>
		<div class="col-md-9 margin-top-s">
			<nav>
				<ol class="nav nav-pills txt-bold pull-right">
					<li><a href="{{ url('features') }}" title="Feature list">features</a></li>
					<li><a href="{{ url('screenshots') }}" title="Screenshots">screenshots</a></li>
					<li><a href="{{ url('download') }}" title="Download Giada, latest version">download</a></li>
					<li><a href="{{ url('documentation') }}" title="Giada documentation area">docs</a></li>
					<li><a href="https://github.com/monocasual/giada" title="Giada @ GitHub">Fork us @ GitHub!</a></li>
					<li><a href="{{ url('source') }}" title="Browse Giada's source code">source</a></li>
					<li><a href="{{ url('forum/') }}" title="Giada forum for end users">forum</a></li>
				</ol>
			</nav>
		</div>
	</div>

	<div class="row margin-top-l">
		<div class="col-md-12 text-center">
			{% if config.assets.adsense %}
			<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
			<!-- giada responsive -->
			<ins class="adsbygoogle"
				style="display:block"
				data-ad-client="ca-pub-1778432007040046"
				data-ad-slot="9025673290"
				data-ad-format="auto">
			</ins>
			<script>
			(adsbygoogle = window.adsbygoogle || []).push({});
			</script>
			{% else %}
			<img src="{{ url('public/img/ads-placeholder-728x90.png') }}" />
			{% endif %}
		</div>
	</div>

</div>
