{% extends 'base.phtml' %}

{% block title %}Cookies Policy - {% endblock %}

{% block description %}, cookies policy{% endblock %}

{% block keywords %}, cookies policy{% endblock %}

{% block metas %}{% endblock %}

{% block styles %}{% endblock %}

{% block scripts %}{% endblock %}

{% block content %}
<div class="container">

	<div class="row margin-top-xl">
		<div class="col-md-12 text-center">
			<h1>Cookies policy.</h1>
		</div>
	</div>

	<div id="documentation" class="row margin-top-xl">
		<div class="col-md-12">

			<h2>Use of cookies</h2>

			<p>The "Site" (giadamusic.com) uses cookies to make our services simple and efficient for users who view pages giadamusic.com. Users viewing the site, will fill the minimal amounts of information in your devices, which are computers and mobile devices, in small text files called "cookies" stored in the directories used by the Web Browser User. There are several types of cookies, some to make more effective use of the Site, other to enable certain functionality.</p>

			<p>Analyzing in detail our cookies allow you to:</p>
			<ul>
			<li><p>store preferences included;</p></li>
			<li><p>avoid re-enter the same information several times during the visit such as user name and password;</p></li>
			<li><p>analyze the use of the services and content provided by giadamusic.com to optimize the browsingexperience and services offered.</p></li>
			</ul>

			<h2>Types of cookies</h2>

			<h3>Technical Cookie</h3>

			<p>This type of cookie allows the proper operation of certain sections of the site. There are two categories: persistent and session.</p>
			<p><strong>Persistent:</strong> once closed the browser are not destroyed but remain up to a preset expiration date</p>
			<p><strong>Session:</strong> they are destroyed every time the browser is closed.</p>

			<p>These cookies, always sent from our domain, are required to view the site and in relation to technical services offered, we will be increasingly used and then sent, unless the user does not change the settings in your browser (thus affecting the display of site pages).</p>

			<h3>Analytical cookies</h3>

			<p>Cookies in this category are used to collect information about the site. Giadamusic.com will use this information in respect of anonymous statistical analysis to improve the use of the Site and to make the content more interesting and relevant to the wishes of users. This type of cookie collects anonymous data on the activity of users and as it came on the Site. The analytical cookies are sent from the same site or from third-party domains.</p>

			<h3>Cookie analysis of third-party services</h3>

			<p>These cookies are used to collect information on the use of the Site by users in anonymous form such as page views, time spent, traffic sources of origin, geographic origin, age, gender and interests for the purposes of marketing campaigns . These cookies are sent from third-party domains external to the Site.</p>

			<h3>Cookies to integrate products and functions of third-party software</h3>

			<p>This type of cookie incorporates features developed by third parties within the pages of the Site as icons and preferences expressed in social networks in order to share the contents of the site or for the use of services, third-party software (such as software generate maps and additional software that offer additional services). These cookies are sent from third-party domains and partner sites that offer their functionality in the pages of the Site.</p>

			<h3>Profiling Cookies</h3>

			<p>Those cookies are needed to create user profiles in order to send advertising messages in line with the preferences expressed by the user within the pages of the Site.</p>

			<p>Giadamusic.com, according to current legislation, it is not required to seek consent for cookies and technical analytics, as necessary to provide the required services.</p>

			<p>For all other types of cookies consent you may be expressed by the user with one or more of the following modes:</p>

			<ul>
			<li><p>By specific configurations of the browser or its programs used to navigate pages that make up the site.</p></li>
			<li><p>By changing settings in the use of third-party services</p></li>
			<li><p>Both of these solutions might prevent you from using or view parts of the Website.</p></li>
			</ul>

			<h3>Web sites and third-party services</h3>

			<p>The Site may contain links to other Web sites that have their own privacy policy which can be different from the one adopted by giadamusic.com and therefore not responsible for these sites.</p>

			<h2>Cookie list</h2>

			<table class="table">

			  <thead>
			    <tr>
			      <th>Cookie</th>
			      <th>Domain</th>
			      <th>Third party cookie</th>
			      <th>Permanent cookie</th>
			      <th>Session cookie</th>
			    </tr>
			  </thead>

			  <tbody>
			    <tr>
			      <td><code>id</code></td>
			      <td>.doubleclick.net</td>
			      <td><code>Third party cookie</code></td>
			      <td><code>Permanent cookie</code></td>
			      <td></td>
			    </tr>

			    <tr>
			      <td><code>_drt_</code></td>
			      <td>.doubleclick.net</td>
			      <td><code>Third party cookie</code></td>
			      <td></td>
			      <td><code>Session cookie</code></td>
			    </tr>

			    <tr>
			      <td><code>lang</code></td>
			      <td>cdn.syndication.twimg.com</td>
			      <td><code>Third party cookie</code></td>
			      <td></td>
			      <td><code>Session cookie</code></td>
			    </tr>

			    <tr>
			      <td><code>PHPSESSID</code></td>
			      <td>.flattr.com</td>
			      <td><code>Third party cookie</code></td>
			      <td></td>
			      <td><code>Session cookie</code></td>
			    </tr>

			    <tr>
			      <td><code>GEUP</code></td>
			      <td>.youtube.com</td>
			      <td><code>Third party cookie</code></td>
			      <td><code>Permanent cookie</code></td>
			      <td></td>
			    </tr>

			    <tr>
			      <td><code>GPS</code></td>
			      <td>.youtube.com</td>
			      <td><code>Third party cookie</code></td>
			      <td></td>
			      <td><code>Session cookie</code></td>
			    </tr>

			    <tr>
			      <td><code>PREF</code></td>
			      <td>.youtube.com</td>
			      <td><code>Third party cookie</code></td>
			      <td><code>Permanent cookie</code></td>
			      <td></td>
			    </tr>

			    <tr>
			      <td><code>NID</code></td>
			      <td>.google.com</td>
			      <td><code>Third party cookie</code></td>
			      <td><code>Permanent cookie</code></td>
			      <td></td>
			    </tr>

			    <tr>
			      <td><code>__cfduid</code></td>
			      <td>.flattr.com</td>
			      <td><code>Third party cookie</code></td>
			      <td><code>Permanent cookie</code></td>
			      <td></td>
			    </tr>

			    <tr>
			      <td><code>PYPF</code></td>
			      <td>.paypalobjects.com</td>
			      <td><code>Third party cookie</code></td>
			      <td></td>
			      <td><code>Session cookie</code></td>
			    </tr>

			    <tr>
			      <td><code>VISITOR_INFO1_LIVE</code></td>
			      <td>.youtube.com</td>
			      <td><code>Third party cookie</code></td>
			      <td><code>Permanent cookie</code></td>
			      <td></td>
			    </tr>

			    <tr>
			      <td><code>YSC</code></td>
			      <td>.youtube.com</td>
			      <td><code>Third party cookie</code></td>
			      <td><code>Permanent cookie</code></td>
			      <td></td>
			    </tr>

			    <tr>
			      <td><code>_gat</code></td>
			      <td>.giadamusic.com</td>
			      <td></td>
			      <td></td>
			      <td><code>Session cookie</code></td>
			    </tr>

			    <tr>
			      <td><code>_ga</code></td>
			      <td>.giadamusic.com</td>
			      <td></td>
			      <td><code>Permanent cookie</code></td>
			      <td></td>
			    </tr>

			  </tbody>

			</table>

		</div>
	</div>

</div>
{% endblock %}
