{% extends 'base.phtml' %}

{% block title %}Privacy - {% endblock %}

{% block description %}, privacy{% endblock %}

{% block keywords %}, privacy{% endblock %}

{% block metas %}{% endblock %}

{% block styles %}{% endblock %}

{% block scripts %}{% endblock %}

{% block content %}
<div class="container">

	<div class="row margin-top-xl">
		<div class="col-md-12 text-center">
			<h1>Privacy policy</h1>
		</div>
	</div>

	<div id="documentation" class="row margin-top-xl">
		<div class="col-md-12">

			<p>At www.giadamusic.com, the privacy of our visitors is of extreme importance to us. This privacy policy document outlines the types of personal information is received and collected by www.giadamusic.com and how it is used.</p>

			<h2>Log files</h2>

			<p>Like many other Web sites, www.giadamusic.com makes use of log files. The information inside the log files includes internet protocol (IP) addresses, type of browser, Internet Service Provider (ISP), date/time stamp, referring/exit pages, and number of clicks to analyze trends, administer the site, track user's movement around the site, and gather demographic information. IP addresses, and other such information are not linked to any information that is personally identifiable.</p>

			<h2>Google Ads</h2>

			<p>Google, as a third party vendor, uses cookies to serve ads on your site. Google's use of the DART cookie enables it to serve ads to your users based on their visit to your sites and other sites on the Internet. Users may opt out of the use of the DART cookie by visiting the Google ad and content network privacy policy.</p>

			<p>Some of our advertising partners may use cookies and web beacons on our site. Our advertising partners include Google Adsense. These third-party ad servers or ad networks use technology to the advertisements and links that appear on www.giadamusic.com send directly to your browsers. They automatically receive your IP address when this occurs. Other technologies (such as cookies, JavaScript, or Web Beacons) may also be used by the third-party ad networks to measure the effectiveness of their advertisements and/or to personalize the advertising content that you see.</p>

			<p>www.giadamusic.com has no access to or control over these cookies that are used by third-party advertisers. You should consult the respective privacy policies of these third-party ad servers for more detailed information on their practices as well as for instructions about how to opt-out of certain practices. www.giadamusic.com's privacy policy does not apply to, and we cannot control the activities of, such other advertisers or web sites.</p>

			<p>If you wish to disable cookies, you may do so through your individual browser options. More detailed information about cookie management with specific web browsers can be found at the browsers' respective websites.</p>

			<h2>Do we disclose any information to outside parties?</h2>

			<p>We do not sell, trade, or otherwise transfer to outside parties your personally identifiable information. This does not include trusted third parties who assist us in operating our website, conducting our business, or servicing you, so long as those parties agree to keep this information confidential. We may also release your information when we believe release is appropriate to comply with the law, enforce our site policies, or protect ours or others rights, property, or safety. However, non-personally identifiable visitor information may be provided to other parties for marketing, advertising, or other uses.</p>

			<h2>Third party links</h2>

			<p>Occasionally, at our discretion, we may include or offer third party products or services on our website. These third party sites have separate and independent privacy policies. We therefore have no responsibility or liability for the content and activities of these linked sites. Nonetheless, we seek to protect the integrity of our site and welcome any feedback about these sites.</p>

			<h2>California Online Privacy Protection Act Compliance</h2>

			<p>Because we value your privacy we have taken the necessary precautions to be in compliance with the California Online Privacy Protection Act. We therefore will not distribute your personal information to outside parties without your consent.</p>

			<h2>Childrens Online Privacy Protection Act Compliance</h2>

			<p>We are in compliance with the requirements of COPPA (Childrens Online Privacy Protection Act), we do not collect any information from anyone under 13 years of age. Our website, products and services are all directed to people who are at least 13 years old or older.</p>

			<h2>Your Consent</h2>

			<p>By using our site, you consent to our website privacy policy.</p>

			<h2>Changes to our Privacy Policy</h2>

			<p>If we decide to change our privacy policy, we will post those changes on this page, and/or update the Privacy Policy modification date below. This policy was last modified on May 13, 2013.</p>

			<h2>Contacting Us</h2>

			<p>If there are any questions regarding this privacy policy you may contact us using the information below:<br /><br />

			www.giadamusic.com<br />
			{{ config.urls.email }}
			</p>
		</div>
	</div>

</div>
{% endblock %}
