{% extends 'base.phtml' %}

{% block title %}Media - {% endblock %}

{% block description %}, media collection{% endblock %}

{% block keywords %}, media, video, audio{% endblock %}

{% block metas %}{% endblock %}

{% block styles %}{% endblock %}

{% block scripts %}{% endblock %}

{% block content %}
<div class="container">

	<div class="row margin-top-xl">
		<div class="col-md-12 text-center">
			<h1>Seeing (and listening) is believing.</h1>
		</div>
	</div>

	<div class="row margin-top-xl">
		<div class="col-md-12 text-center">
			<h2 class="description">Official video tutorials</h2>
		</div>
	</div>

	<div class="row margin-top-xl">
		<div class="col-md-4">
			<a class="media-thumb" href="https://www.youtube.com/watch?v=S_eLFrwVwKY&index=1&list=PLWvg8ZoDDJR267zqagsUe8sWFb0M-81XO" target="_blank">
				<img class="img-responsive" src="http://img.youtube.com/vi/S_eLFrwVwKY/maxresdefault.jpg" alt="Giada tutorial #1 - Initializing channels">
			</a>
		</div>

		<div class="hidden-lg hidden-md margin-top-xl"></div><!-- spacer for mobile -->

		<div class="col-md-4">
			<a class="media-thumb" href="https://www.youtube.com/watch?v=dYKxUZgsB-o&index=9&list=PLWvg8ZoDDJR267zqagsUe8sWFb0M-81XO" target="_blank">
				<img class="img-responsive" src="http://img.youtube.com/vi/dYKxUZgsB-o/maxresdefault.jpg" alt="Giada tutorial #8 - Loop modes overview">
			</a>
		</div>

		<div class="hidden-lg hidden-md margin-top-xl"></div><!-- spacer for mobile -->

		<div class="col-md-4">
			<a class="media-thumb" href="https://www.youtube.com/watch?v=7sU_RbGWNAs&list=PLWvg8ZoDDJR267zqagsUe8sWFb0M-81XO&index=8" target="_blank">
				<img class="img-responsive" src="http://img.youtube.com/vi/7sU_RbGWNAs/maxresdefault.jpg" alt="Giada tutorial #7 - One shot modes overview">
			</a>
		</div>
	</div>

	<div class="row margin-top-m">
		<div class="col-md-4 col-md-offset-4 text-center">
			<a href="https://www.youtube.com/playlist?list=PLWvg8ZoDDJR267zqagsUe8sWFb0M-81XO">➔ Watch all episodes</a>
		</div>
	</div>

	<div class="row margin-top-xl">
		<div class="col-md-12 text-center">
			<h2 class="description">Demo projects</h2>
		</div>
	</div>

	<div class="row margin-top-xl">
		<div class="col-md-4 col-md-offset-2">
			<a class="media-thumb" href="https://www.youtube.com/watch?v=HnwFLpd-gvo&list=PLWvg8ZoDDJR02wx8nwwurd_ceqK8bbW2I&index=1" target="_blank">
				<img class="img-responsive" src="http://img.youtube.com/vi/HnwFLpd-gvo/maxresdefault.jpg" alt="Giada Loop Machine demo #1 - Dubteque">
			</a>
		</div>

		<div class="hidden-lg hidden-md margin-top-xl"></div><!-- spacer for mobile -->

		<div class="col-md-4">
			<a class="media-thumb" href="https://www.youtube.com/watch?v=8gWjzgOitfs&list=PLWvg8ZoDDJR02wx8nwwurd_ceqK8bbW2I&index=2" target="_blank">
				<img class="img-responsive" src="http://img.youtube.com/vi/8gWjzgOitfs/maxresdefault.jpg" alt="Giada Loop Machine demo #2 - The Beauty">
			</a>
		</div>
	</div>

		<div class="row margin-top-xl">
			<div class="col-md-12 text-center">
				<h2 class="description">Feature testing</h2>
			</div>
		</div>

		<div class="row margin-top-xl">
			<div class="col-md-4 col-md-offset-2">
				<a class="media-thumb" href="https://www.youtube.com/watch?list=PLWvg8ZoDDJR1y2oJre2LshwYqS9ieBiAn&v=2h1pallZ020" target="_blank">
					<img class="img-responsive" src="http://img.youtube.com/vi/2h1pallZ020/maxresdefault.jpg" alt="Testing #Giada 2 - (Drag and) Drop da beat">
				</a>
			</div>

			<div class="hidden-lg hidden-md margin-top-xl"></div><!-- spacer for mobile -->
			
			<div class="col-md-4">
				<a class="media-thumb" href="https://www.youtube.com/watch?v=Ge5J6H7k0D4&list=PLWvg8ZoDDJR1y2oJre2LshwYqS9ieBiAn" target="_blank">
					<img class="img-responsive" src="http://img.youtube.com/vi/Ge5J6H7k0D4/maxresdefault.jpg" alt="Testing Giada #1 - High quality pitch control">
				</a>
			</div>
		</div>

</div>
{% endblock %}
