{% extends 'base.phtml' %}

{% block title %}Media - {% endblock %}

{% block description %}, media collection{% endblock %}

{% block keywords %}, media, video, audio{% endblock %}

{% block metas %}{% endblock %}

{% block styles %}{% endblock %}

{% block scripts %}{% endblock %}

{% block content %}
<div class="container">

	<div class="row margin-top-xl">
		<div class="col-md-12 text-center">
			<h1>Seeing (and listening) is believing.</h1>
		</div>
	</div>

	<div class="row margin-top-xl">
		<div class="col-md-12 text-center">
			<h2 class="description">Official video tutorials</h2>
		</div>
	</div>

	<div class="row margin-top-xl">
		<div class="col-md-4">
			<div class="media-thumb">
				<a href="https://www.youtube.com/watch?v=S_eLFrwVwKY&index=1&list=PLWvg8ZoDDJR267zqagsUe8sWFb0M-81XO" target="_blank">
					<img class="img-responsive" src="http://img.youtube.com/vi/S_eLFrwVwKY/maxresdefault.jpg" alt="Giada tutorial #1 - Initializing channels">
				</a>
			</div>
			<h3>Giada tutorial #1 - Initializing channels</h3>
			<p>This is a remake of the first chapter in the amazing series of Giada tutorials. A brief introduction to the concept of channels, how they work and what you can do with them.</p>
		</div>


		<div class="hidden-lg hidden-md margin-top-xl"></div><!-- spacer for mobile -->

		<div class="col-md-4">
			<div class="media-thumb">
				<a href="https://www.youtube.com/watch?v=dYKxUZgsB-o&index=9&list=PLWvg8ZoDDJR267zqagsUe8sWFb0M-81XO" target="_blank">
					<img class="img-responsive" src="http://img.youtube.com/vi/dYKxUZgsB-o/maxresdefault.jpg" alt="Giada tutorial #8 - Loop modes overview">
				</a>
			</div>
			<h3>Giada tutorial #8 - Loop modes overview</h3>
			<p>Another smashing tutorial by Richard Aspromonte! This time he will walk us through the land of Loop modes. You will learn how to handle Giada as a loop machine, building your live performance from the ground up.</p>
		</div>

		<div class="hidden-lg hidden-md margin-top-xl"></div><!-- spacer for mobile -->

		<div class="col-md-4">
			<div class="media-thumb">
				<a href="https://www.youtube.com/watch?v=7sU_RbGWNAs&list=PLWvg8ZoDDJR267zqagsUe8sWFb0M-81XO&index=8" target="_blank">
					<img class="img-responsive" src="http://img.youtube.com/vi/7sU_RbGWNAs/maxresdefault.jpg" alt="Giada tutorial #7 - One shot modes overview">
				</a>
			</div>
			<h3>Giada tutorial #7 - One shot modes overview</h3>
			<p>Our new digital friend Richard Aspromonte introduces us to the joyful world of sample channels. What are "one shot" modes? How can I use them properly? In this tutorial you will learn how to handle Giada as a drum machine/sample player/soundscape generator.</p>
		</div>
	</div>

	<div class="row margin-top-m">
		<div class="col-md-4 col-md-offset-4 text-center">
			<a href="https://www.youtube.com/playlist?list=PLWvg8ZoDDJR267zqagsUe8sWFb0M-81XO">➔ Watch all episodes</a>
		</div>
	</div>

	<div class="row margin-top-xl">
		<div class="col-md-12 text-center">
			<h2 class="description">Demo projects</h2>
		</div>
	</div>

	<div class="row margin-top-xl">
		<div class="col-md-4 col-md-offset-2">
			<div class="media-thumb">
				<a href="https://www.youtube.com/watch?v=HnwFLpd-gvo&list=PLWvg8ZoDDJR02wx8nwwurd_ceqK8bbW2I&index=1" target="_blank">
					<img class="img-responsive" src="http://img.youtube.com/vi/HnwFLpd-gvo/maxresdefault.jpg" alt="Giada Loop Machine demo #1 - Dubteque">
				</a>
			</div>
			<h3>Giada Loop Machine demo #1 - Dubteque</h3>
			<p>Featuring basic looping, one shot samples, MIDI channels, actions and VST processing. Played and recorded on Xubuntu 12.04.</p>
		</div>

		<div class="hidden-lg hidden-md margin-top-xl"></div><!-- spacer for mobile -->

		<div class="col-md-4">
			<div class="media-thumb">
				<a href="https://www.youtube.com/watch?v=8gWjzgOitfs&list=PLWvg8ZoDDJR02wx8nwwurd_ceqK8bbW2I&index=2" target="_blank">
					<img class="img-responsive" src="http://img.youtube.com/vi/8gWjzgOitfs/maxresdefault.jpg" alt="Giada Loop Machine demo #2 - The Beauty">
				</a>
			</div>
			<h3>Giada Loop Machine demo #2 - The Beauty</h3>
			<p>Featuring basic looping, one shot samples, pitch control, VST live processing. Played and recorded on Xubuntu 12.04.</p>
		</div>
	</div>

		<div class="row margin-top-xl">
			<div class="col-md-12 text-center">
				<h2 class="description">Feature testing</h2>
			</div>
		</div>

		<div class="row margin-top-xl">
			<div class="col-md-4 col-md-offset-2">
				<div class="media-thumb">
					<a href="https://www.youtube.com/watch?list=PLWvg8ZoDDJR1y2oJre2LshwYqS9ieBiAn&v=2h1pallZ020" target="_blank">
						<img class="img-responsive" src="http://img.youtube.com/vi/2h1pallZ020/maxresdefault.jpg" alt="Testing #Giada 2 - (Drag and) Drop da beat">
					</a>
				</div>
				<h3>Testing #Giada 2 - (Drag and) Drop da beat</h3>
				<p>In this video we want to test the new drag and drop feature introduced in version 0.9.2. No more "click here and there", please! </p>
			</div>

			<div class="hidden-lg hidden-md margin-top-xl"></div><!-- spacer for mobile -->

			<div class="col-md-4">
				<div class="media-thumb">
					<a href="https://www.youtube.com/watch?v=Ge5J6H7k0D4&list=PLWvg8ZoDDJR1y2oJre2LshwYqS9ieBiAn" target="_blank">
						<img class="img-responsive" src="http://img.youtube.com/vi/Ge5J6H7k0D4/maxresdefault.jpg" alt="Testing Giada #1 - High quality pitch control">
					</a>
				</div>
				<h3>Testing Giada #1 - High quality pitch control</h3>
				<p>Testing the new pitch control introduced in version 0.8.1, based on libsamplerate and way better than the previous one. For this test we used the Amen Break, possibly the most famous sample in the hiphop/dnb/jungle scene (original record: The Winstons - Amen Brother, 1969).</p>
			</div>
		</div>

</div>
{% endblock %}
