{% extends 'base.phtml' %}

{% block title %}Media - {% endblock %}

{% block description %}, media collection{% endblock %}

{% block keywords %}, media, video, audio{% endblock %}

{% block metas %}{% endblock %}

{% block styles %}{% endblock %}

{% block scripts %}{% endblock %}

{% block content %}
<div class="container">

	<div class="row margin-top-xl">
		<div class="col-md-12 text-center">
			<h1>Demos, tutorials, experiments.</h1>
		</div>
	</div>

	<div class="row margin-top-xl">
		<div class="col-md-4">
			col 1
		</div>
		<div class="col-md-4">
			col 2
		</div>
		<div class="col-md-4">
			col 3
		</div>
	</div>

</div>
{% endblock %}
