<div class="container">

	<div class="row margin-top-xl">
		<div class="col-md-12 text-center">
			<h1>A screenshot is worth a thousand words.</h1>
		</div>
	</div>


	<div class="row margin-top-xl">

		<div class="col-md-8 col-md-offset-2">

			<div>
				<p>
					<img class="img-responsive" src="{{ url('public/img/screenshots/giada-loop-machine-screenshot-17.png') }}" alt="Giada 0.9.4: Chopping samples with the advanced Sample Editor">
				</p>
				<p>
					Giada 0.9.4 ― Chopping samples with the advanced Sample Editor.
				</p>
			</div>

			<div class="margin-top-xl padding-top-xl line-top">
				<p>
					<img class="img-responsive" src="{{ url('public/img/screenshots/giada-loop-machine-screenshot-14-carousel.jpg') }}" alt="Giada 0.9.0 in action">
				</p>
				<p>
					Giada 0.9.0 ― Full screen interface with tons of channels.
				</p>
			</div>

			<div class="margin-top-xl padding-top-xl line-top">
				<p>
					<img class="img-responsive" src="http://www.giadamusic.com/img/screenshots/giada-loop-machine-screenshot-13.png" alt="Giada Screenshot">
				</p>
				<p>
					Giada 0.7.0 ― the new Piano Roll in Action Editor for MIDI and VST Instruments.
				</p>
			</div>

			<div class="margin-top-xl padding-top-xl line-top">
				<p>
					<img class="img-responsive" src="http://www.giadamusic.com/img/screenshots/giada-loop-machine-screenshot-12.png" alt="Giada Screenshot">
				</p>
				<p>
					Giada 0.7.0 ― churning out some fat pads with <a href="http://www.loomer.co.uk/aspect.htm" title="Loomer Aspect - Semi-Modular Analogue Synth VST, RTAS, and Audio Unit">Loomer Aspect</a>.
				</p>
			</div>

			<div class="margin-top-xl padding-top-xl line-top">
				<p>
					<img class="img-responsive" src="http://www.giadamusic.com/img/screenshots/giada-loop-machine-screenshot-11.png" alt="Giada Screenshot">
				</p>
				<p>Giada 0.6.2 ― big project with sample editor and action editor.</p>
			</div>

			<div class="margin-top-xl padding-top-xl line-top">
				<p>
					<img class="img-responsive" src="http://www.giadamusic.com/img/screenshots/giada-loop-machine-screenshot-10.png" alt="Giada Screenshot">
				</p>
				<p>Giada 0.6.0 ― full screen sample editor.</p>
			</div>

			<div class="margin-top-xl padding-top-xl line-top">
				<p>
					<img class="img-responsive" src="http://www.giadamusic.com/img/screenshots/giada-loop-machine-screenshot-09.png" alt="Giada Screenshot">
				</p>
				<p>Giada 0.5.7 ― action editor with grid snap feature.</p>
			</div>

			<div class="margin-top-xl padding-top-xl line-top">
				<p>
					<img class="img-responsive" src="http://www.giadamusic.com/img/screenshots/giada-loop-machine-screenshot-08.png" alt="Giada Screenshot">
				</p>
				<p> Giada 0.5.4 ― featuring one of the glorious <a title="TAL Plugins" href="http://kunz.corrupt.ch/">TAL</a> reverbs for Linux.
				</p>
			</div>

			<div class="margin-top-xl padding-top-xl line-top">
				<p>
					<img class="img-responsive" src="http://www.giadamusic.com/img/screenshots/giada-loop-machine-screenshot-07.png" alt="Giada Screenshot">
				</p>
				<p>Giada 0.5.x ― early version of the action editor.</p>
			</div>

			<div class="margin-top-xl padding-top-xl line-top">
				<p>
					<img class="img-responsive" src="http://www.giadamusic.com/img/screenshots/giada-loop-machine-screenshot-04.png" alt="Giada Screenshot">
				</p>
				<p>Giada 0.4.8 ― master out featuring a couple of excellent VST plugins from <a href="http://mda.smartelectronix.com/" target="_blank">MDA</a>.
				</p>
			</div>


			<div class="margin-top-xl padding-top-xl line-top">
				<p>
					<img class="img-responsive" src="http://www.giadamusic.com/img/screenshots/giada-loop-machine-screenshot-03.png" alt="Giada Screenshot">
				</p>
				<p>Giada 0.4.5 ― file browser.</p>
			</div>

		</div>

	</div>

</div><!-- container -->
