<div class="glm-follow-us-popup">

	<div class="glm-follow-us-popup__header">
		<div class="glm-follow-us-popup__header__close"></div>
		<p>Follow us on Facebook!</p>
	</div>

	<div class="glm-follow-us-popup__body">
		<div class="glm-follow-us-popup__body__ok">
			giada on facebook
		</div>
	</div>

	<div class="glm-follow-us-popup__footer">
		<p><a href="#" class="glm-follow-us-popup__footer__nope">Nope, thanks anyway</a></p>
	</div>

</div>
