<div class="glm-follow-us-popup">

	<div class="glm-follow-us-popup__header">
		<div class="glm-follow-us-popup__header__close"></div>
		<p>Follow us on Facebook!</p>
	</div>

	<div class="glm-follow-us-popup__body">
		<div class="glm-follow-us-popup__body__ok">
			<div class="fb-page"
					data-href="https://m.facebook.com/GiadaYourHardcoreLoopmachine"
					data-tabs="" 
					data-small-header="false"
					data-adapt-container-width="true"
					data-hide-cover="false"
					data-show-facepile="true">
				<blockquote cite="https://m.facebook.com/GiadaYourHardcoreLoopmachine" class="fb-xfbml-parse-ignore"><a href="https://m.facebook.com/GiadaYourHardcoreLoopmachine">Giada - Your Hardcore Loopmachine</a></blockquote>
			</div>
		</div>
	</div>

	<div class="glm-follow-us-popup__footer">
		<div><a href="#" class="glm-follow-us-popup__footer__liked">I already like you!</a></div>
		<div><a href="#" class="glm-follow-us-popup__footer__nope">Nope, thanks anyway</a></div>
	</div>

</div>
