<!-- https://developers.facebook.com/docs/plugins/page-plugin -->

<div class="glm-follow-us-popup">

	<div class="glm-follow-us-popup__header">
		<div class="glm-follow-us-popup__header__close"></div>
		<p>Follow us on Facebook!</p>
	</div>

	<div class="glm-follow-us-popup__body">
		<div
			class="fb-page"
			data-href="https://www.facebook.com/GiadaYourHardcoreLoopmachine"
			data-small-header="false"
			data-adapt-container-width="true"
			data-hide-cover="false"
			data-tabs=""
			data-show-facepile="true">
			<blockquote cite="https://www.facebook.com/GiadaYourHardcoreLoopmachine" class="fb-xfbml-parse-ignore">
				<a href="https://www.facebook.com/GiadaYourHardcoreLoopmachine">Giada - Your Hardcore Loopmachine</a>
			</blockquote>
		</div>
	</div>

	<div class="glm-follow-us-popup__footer">
		<p><a href="#" class="glm-follow-us-popup__footer__nope">Nope, thanks anyway</a></p>
	</div>

</div>
