<div class="share-button flattr">
  <a href="https://flattr.com/submit/auto?user_id={{ config.services.flattr_id }}&url={{ config.urls.base | url_encode }}&title={{ config.metas.title | url_encode }}&description={{ config.metas.description | url_encode }}&language=en_GB&tags={{ config.metas.keywords | url_encode }}&category=software">
    <img src="{{ url('img/social-icons-flattr.png') }}" alt="flattr" title="Giada @ Flattr">
    <span>{{ socialStats['flattr'] }}</span>
  </a>
</div>
