{% extends 'base.phtml' %}

{% block title %}News archive - {% endblock %}

{% block description %}, news archive{% endblock %}

{% block keywords %}, news archive{% endblock %}

{% block metas %}{% endblock %}

{% block styles %}{% endblock %}

{% block scripts %}{% endblock %}

{% block content %}
<div class="container">

	<div class="row margin-top-xl">
		<div class="col-md-12 text-center">
			<h1>News archive.</h1>
		</div>
	</div>

	<div class="row">
		<div class="col-md-10 col-md-offset-1">
			{% for n in news %}
			<div class="margin-top-l padding-top-s line-top">
				<h2 class="description">{{ n.getTitle() }}</h2>
				<span class="pull-left margin-right-s"><span class="red">{{ n.getDate() }}</span> ― </span> {{ n.getText() }}
			</div>
			{% endfor %}
		</div>
	</div>

</div>
{% endblock %}
