<!DOCTYPE html>
<html>
	<head lang="{% block lang %}en{% endblock %}">
		<title>{% block title %}{% endblock %}{{ meta_title }}</title>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<meta name="author" content="{{ config.metas.author }}">
		<meta name="description" content="{% block description %}{% endblock %}">
		<meta name="keywords" content="{% block keywords %}{% endblock %}">
		<meta name="copyright" content="{{ config.metas.copyright }}">
		<meta name="application-name" content="{{ config.metas.title }}">
		{% block metas %}{% endblock %}

		<link rel="shortcut icon" href="{{ url('img/favicon.ico') }}" type="image/x-icon">
		<link rel="stylesheet" href="{{ url('css/main-' ~ config.assets.version ~ '.css') }}" type="text/css">
		{% block styles %}{% endblock %}

		<!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
		<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
		<!--[if lt IE 9]>
			<script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
			<script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
		<![endif]-->

		{% if config.assets.analytics %}
		<script>
			(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
			(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
			m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
			})(window,document,'script','//www.google-analytics.com/analytics.js','ga');
			ga('create', 'UA-23296419-18', 'auto');
			ga('require', 'displayfeatures');
			ga('send', 'pageview');
		</script>
		{% endif %}

	</head>
	<body>
		{% include 'partials/header.phtml' %}
		{% block content %}{% endblock %}
		{% include 'partials/footer.phtml' %}
		{% block scripts %}{% endblock %}
	</body>
</html>
