
<h1>The Action Editor</h1>

<p style="display: inline-block;"><img src="{{ url('img/docs/action-editor-window.png') }}" alt="The action editor" title="The action editor" class="first" /> The <strong>action editor</strong> is a tool to operate on actions. Here you can alter and modify the existing ones, as well as add them from scratch. It represents the actions of a channel and it's composed of several horizontal widgets, each of them containing a specific action type.</p>
<div class="clear"></div>



<h2>General interactions</h2>
<p>All the widgets work the same way: you manage them with the mouse and you add, remove or shift the actions by clicking on them.
<table class="table">
	<tr>
		<th>action</th>
		<th>effect</th>
	</tr>
	<tr>
		<td><span class="code">left click</span> on empty area</td>
		<td>add an action</td>
	</tr>
	<tr>
		<td><span class="code">right click</span> on action</td>
		<td>remove an action</td>
	</tr>
	<tr>
		<td><span class="code">left click</span> + drag on action</td>
		<td>move the action or resize it</td>
	</tr>
	<tr>
		<td><span class="code">right click</span> + drag on empty area</td>
		<td>vertical scroll, if the widget has scrollable content</td>
	</tr>
</table>
</p>
<p>The <strong>zoom buttons</strong> <img src="{{ url('img/docs/zoom-buttons.png') }}" alt="Zoom buttons" title="Zoom buttons" class="inline" /> in the upper right corner of the window allow to magnify or reduce the view of all the widgets. The <strong>grid tool</strong> <img src="{{ url('img/docs/giada-action-editor-snap-grid.png') }}" alt="Grid tool" title="Grid tool" class="inline" /> shows a visual grid over the beat cells; the small check button on the right enables snapping.</p>



<h2>Available actions</h2>
<p>At the moment the action editor allows to manage the following action types:</p>
<ul>
<li>key press, key release, sample kill — through the <strong>start/stop</strong> widget;</li>
<li>mute — through the <strong>mute</strong> widget;</li>
<li>volume — through the <strong>volume envelope</strong> widget.</li>
<li>MIDI events — through the <strong>piano roll</strong> widget.</li>
</ul>



<h2>Start/stop widget</h2>

<p>The <strong>start/stop</strong> widget <img src="{{ url('img/docs/action-widget.png') }}" title="Action widget" alt="Action widget" class="first" />works only for those channels set in <strong>oneshot mode</strong> (<img src="{{ url('img/docs/mode_loopc.png') }}" title="Oneshot basic" alt="Oneshot basic" class="inline" /><img src="{{ url('img/docs/mode_loopd.png') }}" tile="Oneshot press" alt="Oneshot press" class="inline" /><img src="{{ url('img/docs/mode_loope.png') }}" title="Oneshot retrig" alt="Oneshot retrig" class="inline" /><img src="{{ url('img/docs/mode_loopg.png') }}" title="Oneshot endless" alt="Oneshot endless" class="inline" />); if you open the editor for a channel set in <strong>loop mode</strong>, the widget will be disabled. Actions are represented in different ways:</p>
<ul>
<li><strong>Key press</strong> <img src="{{ url('img/docs/action-keypress.png') }}" title="Action keypress" alt="Action keypress" class="inline" /> — a single key pressure, usually recorded live with <span class="code">[key]</span>;</li>

<li><strong>Key release</strong> <img src="{{ url('img/docs/action-keyrel.png') }}" title="Action keyrel" alt="Action keyrel" class="inline" /> — a single key release;</li>

<li><strong>Kill chan</strong> <img src="{{ url('img/docs/action-killchan.png') }}" title="Action kill chan" alt="Action kill chan" class="inline" /> — a sample break, usually recorded live with <span class="code">shift+[key]</span>;</li>

<li><strong>Composite action</strong> <img src="{{ url('img/docs/action-composite.png') }}" title="Composite action" alt="Composite action" class="inline" /> — it represents the combination of a <em>key press</em> + <em>key release</em> and it's available only for channels set to <strong>oneshot press</strong> mode <img src="{{ url('img/docs/mode_loopd.png') }}" tile="Oneshot press" alt="Oneshot press" class="inline" />. It shows the <em>duration</em> of the key pressure and you can resize it by dragging the edges.</li>
</ul>

<p>The <strong>action type selector</strong> <img src="{{ url('img/docs/action-type.png') }}" alt="Action type selector" title="Action type selector" class="inline" /> changes the action drawn by the cursor.</p>

<div class="clearfix"></div>

<h2>Mute widget</h2>

<p>The <strong>mute</strong> widget <img src="{{ url('img/docs/mute-widget.png') }}" title="Mute widget" alt="Mute widget" class="first" />works for any mode set for channels. The squared dots can be dragged around and they represent a change of status. Mute is active when the line is at the top.</p>

<div class="clearfix"></div>

<h2>Volume Envelope widget</h2>

<p>The <strong>volume envelope</strong> widget <img src="{{ url('img/docs/volume-envelope-widget.png') }}" title="Volume Envelope widget" alt="Volume Envelope widget" class="first" /> handles volume changes. It ranges from 0 (bottom, silence) to 1 (top, full amplitude). Click on the first or last point to erase the envelope completely.</p>

<div class="clearfix"></div>

<h2>Piano roll widget</h2>

<p>Available only for <strong>MIDI channels</strong>, the <strong>piano roll</strong> widget <img src="{{ url('img/docs/piano-roll-widget.png') }}" title="Piano Roll widget" alt="Piano Roll widget" class="first" /> handles MIDI notes. It represents the full set of 128 notes (0-127) with 11 octaves ranging from C-1 (or C0) to G9 (or G10).</p>

<p>It can be vertically resized by dragging the lower edge up and down. <em>Left-click</em> on an empty space and drag it to move the grid up and down.</p>

<p>Starting from version 0.13.4 the piano roll editor is able to cope with wrong MIDI events, such as two Note On next to each other. We call them <strong>orphaned MIDI events</strong> and they look like an empty rectangle <img src="{{ url('img/docs/action-orphaned.png') }}" alt="Orphaned MIDI event" title="Orphaned MIDI event" class="inline" /> with fixed width.</p>

<p>You can't do much with an orphaned MIDI event, except for deleting it by right clicking on it. Useful to clean up a MIDI mess.</p>

<div class="clearfix"></div>
