
<h1>Channels and Samples</h1>

<p>
A <strong>Sample channel</strong> contains one sample. By clicking on its <strong>main button</strong> <img src="{{ url('img/docs/sample-button.png') }}" alt="Main button" title="Main button" class="inline" /> you will be able to load a new sound as well as doing further operations. You can add a new channel by clicking on the "Add new channel" button on top of each column, or by drag-and-dropping a file over the empty space of any column.</p>

<h2>Case 1: the channel is empty</h2>

<p>A file browser lets you choose the new sample. Thanks to <a href="http://www.mega-nerd.com/libsndfile/" title="libsndfile">libsndfile</a> Giada is able to load a large number of uncompressed file formats, most especially WAV, AIFF and RAW. If the loading procedure is successful the sample is ready to play. You may also load a new sample by dragging and dropping a file into any existing channel.</p>


<h2>Case 2: the channel is not empty</h2>

<p>A popup menu appears with several options.</p>
<p><img src="{{ url('img/docs/channel-button-menu.png') }}" alt="Channel button's menu" title="Channel button's menu" /></p>
<ul>
<li>
	<strong>Input monitor</strong> — when enabled, it will allow you to monitor (i.e. listen to) the live input to an armed channel. This option can be set to on or off by default in the <a href="{{ url('documentation/show/configuration') }}">configuration window</a>, "Behaviors" tab;
</li>
<li>
	<strong>Load new sample</strong> — replaces the current sample with a new one. Volume, actions, mode will be	preserved;
</li>
<li>
	<strong>Export sample to file</strong> — writes the loaded sample to disk. This option is useful to export a single take without saving the entire project (more infos in section <a href="{{ url('documentation/show/save-load-export') }}">Save, load, export</a>);
</li>
<li>
	<strong>Set key</strong> — binds keys to channel;
</li>
<li>
	<strong>Setup MIDI input</strong> — binds MIDI events to channel, see <a href="{{ url('documentation/show/midi-input-management') }}">MIDI input management</a>;
</li>
<li>
	<strong>Edit sample</strong> — opens a new window of the <a href="{{ url('documentation/show/sample-editor') }}">sample editor</a>;
</li>
<li>
	<strong>Edit actions</strong> — opens a new window of the <a href="{{ url('documentation/show/action-editor') }}">action editor</a>;
</li>
<li>
	<strong>Clear actions</strong> — deletes recorded actions from the channel: key press/key release, mute, volume or everything. The option is grayed out if there are no actions to delete;
</li>
<li>
	<strong>Free channel</strong> — discharges the sample and the recorded actions, if any. Volume and mode will be preserved.
</li>
<li>
	<strong>Delete channel</strong> — removes the channel from the stack. Actions and samples will be deleted as well.
</li>
</ul>
<div class="clear"></div>


<h2>Channel statuses</h2>

<p>The <strong>status box</strong> <img src="{{ url('img/docs/status-box.png') }}" alt="Status box" title="Status box" class="inline" /> gives you informations about the sample:
</p>

<ul>
<li>
	<img src="{{ url('img/docs/chanstatus_off.png') }}" alt="Chan status off" title="Chan status off" class="inline" /> <strong>Off</strong> — the channel is stopped;
</li>
<li>
	<img src="{{ url('img/docs/chanstatus_wait.png') }}" alt="Chan status wait" title="Chan status wait" class="inline" /> <strong>Wait/ending</strong> (blinking) — the channel is waiting for the first beat or is about to stop;
</li>
<li>
	<img src="{{ url('img/docs/chanstatus_play.png') }}" alt="Chan status play" title="Chan status play" class="inline" /> <strong>Play</strong> — the channel is active and playing;
</li>
<li>
	<img src="{{ url('img/docs/chanstatus_actionrec_on.png') }}" alt="Chan status action recs on" title="Chan status action recs on" class="inline" /> <strong>Action recs on</strong>  — the channel is ready to record actions;
</li>
<li>
	<img src="{{ url('img/docs/chanstatus_inputrec_on.png') }}" alt="Chan status input recs on" title="Chan status input recs on" class="inline" />
	<strong>Input recs on</strong> — the channel is recording something from the soundcard.
</li>
</ul>

<h2>Play modes</h2>

<p>Play modes define the behavior of a <strong>sample channel</strong>. As said before, they are divided into two families: <strong>loop</strong> and <strong>one shot</strong>. Main features of <strong>loop modes</strong>:</p>

<ul>
<li>work only when the sequencer is running;</li>
<li>constrained to the sequencer's boundaries;</li>
<li>triggered manually: you can't record keypress/keyrelease actions on them.</li>
</ul>

<p>Main features of <strong>one shot modes</strong>:</p>

<ul>
<li>independent from the sequencer;</li>
<li>you can record actions on them.</li>
</ul>


<table class="table">
	<tr>
		<th>icon</th>
		<th>type</th>
		<th>name</th>
		<th>effect</th>
	</tr>

	<tr>
		<td><img src="{{ url('img/docs/mode_loopa.png') }}" alt="Loop basic" title="Loop basic" /></td>
		<td>loop</td>
		<td>loop basic</td>
		<td>the sample starts at beat 1 and will play continuously until its key is pressed</td>
	</tr>

	<tr>
		<td><img src="{{ url('img/docs/mode_loopb.png') }}" alt="Loop once" title="Loop once" /></td>
		<td>loop</td>
		<td>loop once</td>
		<td>the sample starts at beat 1 and will play until finished. Then, at the next first beat it starts again</td>
	</tr>

	<tr>
		<td><img src="{{ url('img/docs/loop-once-bar.png') }}" alt="Loop once bar" title="Loop once bar" /></td>
		<td>loop</td>
		<td>loop once bar</td>
		<td>similar to the previous mode, but the sample starts again also on the next first bar</td>
	</tr>

	<tr>
		<td><img src="{{ url('img/docs/mode_loopf.png') }}" alt="Loop repeat" title="Loop repeat" /></td>
		<td>loop</td>
		<td>loop repeat</td>
		<td>the sample starts at beat 1 and will play continuously, rewinding itself at every bar</td>
	</tr>

	<tr>
		<td><img src="{{ url('img/docs/mode_loopc.png') }}" title="Oneshot basic" alt="Oneshot basic" /></td>
		<td>one shot</td>
		<td>one shot basic</td>
		<td>the sample starts on key press and stops on a second keypress</td>
	</tr>

	<tr>
		<td><img src="{{ url('img/docs/mode_loopd.png') }}" tile="Oneshot press" alt="Oneshot press" /></td>
		<td>one shot</td>
		<td>one shot press</td>
		<td>the sample plays as long as its key is pressed</td>
	</tr>

	<tr>
		<td><img src="{{ url('img/docs/mode_loope.png') }}" title="Oneshot retrig" alt="Oneshot retrig" /></td>
		<td>one shot</td>
		<td>one shot retrig</td>
		<td>the sample plays until the end; pressing its key rewinds it</td>
	</tr>

	<tr>
		<td><img src="{{ url('img/docs/mode_loopg.png') }}" title="Oneshot endless" alt="Oneshot endless" /></td>
		<td>one shot</td>
		<td>one shot endless</td>
		<td>the sample plays in loop forever; pressing its key stops it</td>
	</tr>

</table>


<h2>Keyboard interactions</h2>

<p><strong>Sample channels</strong> are playable either by pressing the key associated or clicking with the mouse on the channel's <strong>key box</strong> <img src="{{ url('img/docs/key-box.png') }}" alt="Key box" title="Key box" class="inline" />. The following table shows what happens with channels in <strong>loop</strong> mode:</p>

<table class="table">
	<tr>
		<th>mode</th>
		<th style="width:150px">event</th>
		<th>alt. event</th>
		<th>result</th>
	</tr>

	<tr>
		<td rowspan="4">loop</td>
	</tr>

	<tr>
		<td><span class="code">[key]</span></td>
		<td>click on the key box</td>
		<td>wait, then start/stop on next beat 1</td>
	</tr>
	<tr>
		<td><span class="code">shift + [key]</span></td>
		<td><span class="code">shift</span> + click on the key box</td>
		<td>immediate stop</td>
	</tr>
	<tr>
		<td><span class="code">control + [key]</span></td>
		<td>click on <strong>mute</strong> button <img src="{{ url('img/docs/mute-button.png') }}" alt="Mute button" title="Mute button" class="inline" /></td>
		<td>mute</td>
	</tr>
</table>

<p>The following table shows what happens with channels in <strong>one shot</strong> mode:</p></p>

<table class="table">
	<tr>
		<th>mode</th>
		<th style="width:150px">event</th>
		<th>alt. event 1</th>
		<th>alt. event 2</th>
		<th>result</th>
	</tr>

	<tr>
		<td rowspan="4">one shot</td>
	</tr>

	<tr>
		<td><span class="code">[key]</span></td>
		<td>click on the key box</td>
		<td>-</td>
		<td>start</td>
	</tr>
	<tr>
		<td><span class="code">shift + [key]</span></td>
		<td><span class="code">shift</span> + click on the key box</td>
		<td>click on <strong>read actions</strong> button <img src="{{ url('img/docs/read-recs-button.png') }}" alt="Read recordings button" title="Read recordings button" class="inline" /></td>
		<td>immediate stop if channel has no actions, else start/stop reading actions (see below)</td>
	</tr>
	<tr>
		<td><span class="code">control + [key]</span></td>
		<td>click on <strong>mute</strong> button <img src="{{ url('img/docs/mute-button.png') }}" alt="Mute button" title="Mute button" class="inline" /></td>
		<td>-</td>
		<td>mute</td>
	</tr>
</table>

<h2>Sample channels with actions</h2>

<p>As soon as the channel in <strong>one shot</strong> mode has some actions recorded into it, the <strong>read actions</strong> button <img src="{{ url('img/docs/read-recs-button.png') }}" alt="Read recordings button" title="Read recordings button" class="inline" /> appears on the right. If you disable it, Giada no longer reads the actions for that channel. That's slightly different from the <strong>mute button</strong>, because you can still play the sample manually and hear it.</p>

<p>By default when you disable the "R" button the actions stop immediately. By checking the <em>treat recorded channels as loops</em> flag in the <a href="{{ url('documentation/show/configuration') }}">configuration</a> panel the actions will stop at the next first beat, as a channel in <strong>loop</strong> mode would do.</p>
