
<h1>Configuration</h1>

<p>
This panel gives you the ability to tweak hardware parameters as well as operational modes, through	three different tabs: <strong>Sound System</strong>, <strong>MIDI</strong> and <strong>Behaviors</strong>.
</p>

<h2>Sound System</h2>

<p>Configure your sound system, input/output channels and the buffer size.</p>
<p><img src="{{ url('img/giada-configuration-panel.png') }}" alt="Giada configuration panel - sound system tab" title="Giada configuration panel - sound system tab" class="first" /></p>
<ul>
<li><strong>System</strong> — This is the audio framework to choose from. It may vary from OS to OS.</li>

<li><strong>Buffer size</strong> — (in frames): a low value	means low latency but high cpu work, while an high value means high latency with low cpu work 	(useful if you have a slow machine or you don't	need to play channels in live mode).</li>

<li><strong>Sample rate</strong> — (in Hz): the sample rate at which your soundcard works. If you load a set of samples recorded at different sample rates, they will be converted to that rate (see <em>resampling</em> below).</li>

<li><strong>Output device</strong> — The device used for playing. The question mark on the right pops up some informations about it.</li>

<li><strong>Limit output</strong> — If enabled, the output signal will be truncated if greater than ± 1.0 (floating point values).</li>

<li><strong>Input device</strong> — The device used for recording. Disabled by default. The question mark on the right pops up some informations about it.</li>

<li><strong>Rec delay comp</strong> — Too much latency can make it difficult to record a live performance: the record delay compensation (in frames) helps you to align the incoming audio to the rest of	your existing beats.</li>

<li><strong>Resampling</strong> — The algorithm used for resampling, i.e. when you load a sample whose sample rate differs from the system's rate. You can choose between five algorithms:
	<ol>
		<li><strong>Linear</strong> — very fast, low quality;</li>
		<li><strong>Zero Order Hold</strong> — fast, low quality;</li>
		<li><strong>Sinc basic quality</strong> — not so fast, medium quality;</li>
		<li><strong>Sinc medium quality</strong> — not fast, good quality;</li>
		<li><strong>Sinc best quality</strong> — slow, super quality.</li>
	</ol>
</li>
</ul>

<h2>MIDI</h2>

<p>Configure here the global MIDI parameters.</p>

<ul>
<li><strong>System</strong> — This is the MIDI framework to choose from. It may vary from OS to OS;</li>
<li><strong>Output port</strong> — The MIDI output connection;</li>
<li><strong>Input port</strong> — The MIDI input connection;</li>
<li><strong>Sync</strong> — How to sync with another device. Giada can act only as a <em>master</em> controller:
	<ol>
		<li><strong>(disabled)</strong> — don't sync anything;</li>
		<li><strong>MIDI Clock</strong> — send <a href="http://en.wikipedia.org/wiki/MIDI_beat_clock">MIDI clock events</a>, aka MIDI beat clock or MIDI clock;</li>
		<li><strong>MTC</strong> — send <a href="http://en.wikipedia.org/wiki/MIDI_timecode">MIDI timecode events</a>. This is quite experimental: the rate is temporarily hardcoded to 25 frame/s (standard rate for PAL video).</li>
	</ol>
</li>
</ul>

<h2>Behaviors</h2>

<p>Define how Giada should handle loops, timing and channels.</p>
<p><img src="{{ url('img/giada-behaviors-panel.png') }}" alt="Giada behaviors panel" title="Giada behaviors panel" class="first" /></p>
<ul>
<li><strong>When a channel with recorded action is halted</strong> — This options defines the behavior  when you stop of a channel with	some actions recorded with by cliking on the "R" button <img src="{{ url('img/read-recs-button.png') }}" alt="Read recordings button" title="Read recordings button" class="inline" /> (or the <span class="code">shift + [key]</span> combination). If you check <em>stop it immediately</em>, the sample will stop abruptly; otherwise with <em>play it until finished</em> the sample will play until it reaches its end.</li>

<li><strong>When the sequencer is halted</strong> — What should happen when you pull up the performance (by pressing the <span class="code">spacebar</span>	or the stop button)? If you choose <em>stop immediately all dynamic channels</em> any sample in loop mode	and any sample with recorded actions will stop abruptly; otherwise with <em>play all dynamic channels until finished</em>, those samples will play until the end.</li>

<li><strong>Treat recorded channels as loops</strong> — By default a click on the "R" button <img src="{{ url('img/read-recs-button.png') }}" alt="Read recordings button" title="Read recordings button" class="inline" /> (or the <span class="code">shift + [key]</span>	combination) stops immediately any recorded action. When this option is enabled any channel whose actions	are suspended puts itself in ending mode, as the loop mode would do, and stops at the next first beat.
</li>

<li><strong>Bring channels to full volume on sample load</strong> — a useful time saver.</li>
</ul>

<h2>Misc</h2>

<p>This tab contains miscellaneous options.</p>

<ul>
<li><strong>Debug messages</strong> — How Giada prints informations on its internal state:
	<ol>
		<li><strong>(disabled)</strong> — don't print anything anywhere;</li>
		<li><strong>To standard output</strong> — print messages on the command line, only if you run Giada from the terminal. This mode doesn't work on Windows;</li>
		<li><strong>To file</strong> — save messages to <span class="code">giada.log</span>, located in the same place of the configuration file as described in the <a href="{{ url('documentation/show/introduction') }}">introduction</a> chapter.</li>

	</ol>
</li>
</ul>
