
<h1>Save, Load, Export</h1>

<p>
Giada is able to produce three kinds of files: <strong>patches</strong>, <strong>projects</strong> and <strong>samples</strong>.
</p>


<h2>Patch</h2>
<p>A <strong>patch</strong> is a text-based <em>.gptc</em> file in which volumes, samples, statuses and configurations are stored. Use this one if you are using samples from your collection (i.e. no takes or any destructive editing done) and you are sure of opening the patch in the same system you saved it. Path: <em>file -&gt; save patch...</em>
</p>


<h2>Project</h2>
<p>Any take from the outside world and/or any destructive editing on the samples must be stored somewhere in order to be used the next time you load your patch. This function creates a <em>.gprj</em> folder in your filesystem, then copies all of your samples inside the folder and creates the <em>.gptc</em> file	in which all sample paths are made relative to that folder.	Path: <em>file -&gt; save project...</em>
</p>


<h2>Samples</h2>
<p>
This function exports the sample to file. At the moment <sup>June 2014, version 0.8.4</sup> only WAV format is supported. Path: <em>[sample button] -&gt; export sample to file...</em>
</p>

<h2>Other interesting options</h2>

<p><img src="{{ url('img/docs/edit-menu-popup.png') }}" alt="Edit menu" title="Edit menu" class="first" />The <strong>edit button</strong> <img src="{{ url('img/edit-button.png') }}" alt="Edit button" title="Edit button" class="inline" /> in the main window offers some other useful options for your work:</p>

<ul>
<li>
	<strong>Clear all samples</strong> — unloads all channels. Modes, volumes and FXs remain untouched;
</li>
<li>
	<strong>Clear all actions</strong> — removes any type of action from all the channels;
</li>
<li>
	<strong>Remove empty columns</strong> — removes all columns containing no samples;
</li>
<li>
	<strong>Reset to init state</strong> — resets Giada to the default blank patch;
</li>
<li>
	<strong>Setup global MIDI input</strong> — binds MIDI events to global parameters, see <a href="{{ url('documentation/show/midi-input-management') }}">MIDI input management</a>.
</li>
</ul>
