
<h1>Recording actions</h1>

<p>You know that an <strong>action</strong> is basically something you do on a channel.	Before doing anything, Giada must be put in <em>record mode</em>. You can do this by	clicking on the <strong>action rec button</strong> <img src="{{ url('img/action-recorder-button.png') }}" alt="Action recorder button" title="Action recorder button" class="inline" /> or by pressing the <span class="code">enter</span> key: all the recordable channels	will turn red. When you're done, disable the record mode: you will notice that all the channels with something recorded	show a "R" button <img src="{{ url('img/read-recs-button.png') }}" alt="Read recordings button" title="Read recordings button" class="inline" />: this one enables or disables the recordings. If you need to erase the actions of a channel, click	on the sample button and select <em>clear recordings</em>, or tweak them more thoroughly in the <a href="{{ url('documentation/show/action-editor') }}">action editor</a>.
</p>

<h2>What types of action can I record?</h2>

<p>For the time being <sup>June 2014, version 0.8.4</sup>, on a <strong>sample channel</strong> you can record the following types:</p>
<ul>
<li>key press;</li>
<li>key release;</li>
<li>sample kill;</li>
<li>channel mute.</li>
</ul>

<p>On a <strong>MIDI channel</strong> you can't do anything live, for now <sup>June 2014, version 0.8.4</sup>. </p>
