
<h1>Channels and MIDI</h1>

<p>
A <strong>MIDI channel</strong> contains MIDI events. By clicking on the <strong>main button</strong> <img src="{{ url('img/midi-button.png') }}" alt="Main button" title="Main button" class="inline" /> a popup menu will appear, with several options available:
</p>

<p><img src="{{ url('img/docs/channel-midi-button-menu.png') }}" alt="MIDI Channel button's menu" title="MIDI Channel button's menu" /></p>
<ul>
<li>
	<strong>Edit actions</strong> — opens a new window of the <a href="{{ url('documentation/show/action-editor') }}">Action Editor</a>;
</li>
<li>
	<strong>Clear actions</strong> — deletes recorded actions from the channel: <em>all</em> is the only option by now <sup>June 2014, version 0.8.4</sup>;
</li>
<li>
	<strong>Setup MIDI output</strong> — opens the <strong>MIDI output setup</strong> window (see below);
</li>
<li>
	<strong>Setup MIDI input</strong> — binds MIDI events to channel, see <a href="{{ url('documentation/show/midi-input-management') }}">MIDI input management</a>;
</li>
<li>
	<strong>Delete channel</strong> — removes the channel from the stack. All MIDI actions will be deleted as well.
</li>
</ul>
<div class="clear"></div>

<h2>Channel statuses</h2>

<ul>
<li>
	<img src="{{ url('img/chanstatus_off.png') }}" alt="Chan status off" title="Chan status off" class="inline" /> <strong>Off</strong> — the channel is stopped;
</li>
<li>
	<img src="{{ url('img/chanstatus_wait.png') }}" alt="Chan status wait" title="Chan status wait" class="inline" /> <strong>Wait/ending</strong> (blinking) — the channel is waiting for the first beat or is about to stop;
</li>
<li>
	<img src="{{ url('img/chanstatus_wait.png') }}" alt="Chan status wait" title="Chan status wait" class="inline" /> <strong>Play</strong> (fixed) — the channel is active and playing;
</li>
</ul>


<h2>Keyboard interactions</h2>

<p>This type of channels are somewhat simplier: they just behave like <strong>sample channels</strong> in <strong>loop basic</strong> mode (quiz: can you figure out why?).
</p>

<table class="table">
	<tr>
		<th>event</th>
		<th>result</th>
	</tr>

	<tr>
		<td>click on the key box</td>
		<td>wait, then start/stop on next beat 1</td>
	</tr>
	<tr>
		<td><span class="code">shift</span> + click on the key box</td>
		<td>immediate stop</td>
	</tr>
	<tr>
		<td>click on <strong>mute</strong> button <img src="{{ url('img/mute-button.png') }}" alt="Mute button" title="Mute button" class="inline" /></td>
		<td>mute</td>
	</tr>
</table>

<h2>MIDI output setup</h2>

<p> <img src="{{ url('img/setup-midi-output.png') }}" alt="Setup MIDI output" title="Setup MIDI output" class="first" /> This panel enables or disables the MIDI output. If you check <em>enable MIDI output</em>, MIDI messages will be sent outside Giada whenever an action occurs, through the channel specified with the drop-down menu on the right. With this technique you will be able to control external MIDI hardware or other software as well.</p>
