

<h1>Compiling from source</h1>

<p>
The configure script inside the package is designed for Unix systems and MinGW (Windows).	It will help you to guess correct values for various system-dependent variables used during compilation. You have to pass it the <span class="code">--target</span> parameter depending on your operating system:
</p>
<p class="code">
./configure --target=[linux | osx | windows]
</p>
<p>
e.g. if you want to compile for Linux, do:
</p>
<p class="code">
./configure --target=linux
</p>
<p>
When the script is done without errors, change directory to <span class="code">src</span>	then type</p>
<p class="code">
make libs
</p>
<p>
in order to compile the included libraries, and finally
</p>
<p class="code">
make
</p>
<p>
to compile everything. If you wish to install Giada on Linux, become root and type
</p>
<p class="code">
	make install
</p>
<p>
to copy the binary file into /usr/local/bin path.
</p>



<h2>Dependencies</h2>
<p>
Giada is based upon <a href="http://www.fltk.org/" title="FLTK GUI Toolkit">FLTK</a> (GUI), <a href="http://www.mega-nerd.com/libsndfile/" title="libsndfile">libsndfile</a>, <a href="http://www.mega-nerd.com/SRC/" title="libsamplerate">libsamplerate</a>, <a href="http://www.music.mcgill.ca/~gary/rtmidi/" title="RtMidi">RtMidi</a> and <a href="http://www.music.mcgill.ca/~gary/rtaudio/" title="rtAudio">RtAudio</a>. At the present moment <sup>August 2014, version 0.9.0</sup> we suggest you to use the following versions:
</p>

<ul>
<li>FLTK — 1.3.[0 or greater];</li>
<li>libsndfile — 1.0.25 or greater;</li>
<li>libsamplerate — 0.1.8 or greater;</li>
<li>RtMidi — 2.1.0 or greater;</li>
<li>RtAudio — 4.1.1 or greater.</li>
</ul>

<p>We also hacked RtAudio library to provide full Jack Transport support for Linux, so if you wish to compile Giada under that OS you have to apply a little patch to your vanilla RtAudio. Don't worry, it's easy!</p>

<p>Unzip the Giada's source package, browse to <span class="code">src/rtaudio</span> and apply the patch you may find inside to your local copy of RtAudio. Then, install it as usual. The modifications we made are minimal and won't affect the main functionalities of the library: we just added a couple of lines of code in order to expose some class properties. You <em>don't</em> have to patch RtAudio if you compile Giada under Windows or OS X.</p>


<h2>How to enable VST support</h2>
<p>
In order to compile Giada with VST support you have to enable the feature via configure script. Add
the following parameter:
</p>
<p class="code">
--enable-vst
</p>
<p>
e.g. if you want to compile for Linux with VST support, do:
</p>
<p class="code">
./configure --target=linux --enable-vst
</p>



<h2>Missing headers!</h2>
<p>
You won't find any VST header into our source package, since we cannot distribute the SDK from Steinberg.
To solve this issue:
</p>
<ol>
	<li>
		go to the <a href="http://www.steinberg.net/en/company/developer.html" target="_blank">Steinberg third-party developer support site</a>,
		login into the developer zone and download VST Audio Plugins SDK (latest version);
	</li>

	<li>
		create a new folder called <span class="code">vst</span> inside <span class="code">Giada/src</span>;
	</li>

	<li>
		extract all files from the VST SDK package, browse to <span class="code">pluginterfaces/vst2.x</span>, grab <span class="code">aeffect.h</span>, <span class="code">aeffectx.h</span> and <span class="code">vstfxstore.h</span> and put	them inside the new <span class="code">vst</span> folder;
	</li>

	<li>
		start compilation and cross your fingers.
	</li>
</ol>
