
<h1>Live sampling</h1>

<p>Giada gives you the ability to record anything coming in from your soundcard thanks to its live sampler and master input channel. Configure your device in the <a href="{{ url('documentation/show/configuration') }}">Configuration panel</a> first, then turn up the knob of the <strong>input volume</strong> <img src="{{ url('img/gui_inputmeter.png') }}" alt="The input peakmeter" title="The input peakmeter" class="inline" /> in the main window.</p>

<p>
The button between the input and the output meter is the <strong>stream linker</strong> <img src="{{ url('img/input-output-linker.png') }}" alt="Input to output linker" title="Input to output linker" class="inline" />: enable it and you will be able to hear what you're playing. Finally you can process the incoming signal by adding some effects on the input side, with the <strong>FX button</strong> <img src="{{ url('img/fx-button.png') }}" alt="FX button" title="FX button" class="inline" />: more informations in the section <a href="{{ url('documentation/show/fx-stack') }}">The FX stack</a>.</p>


<h2>How to use the live sampler</h2>

<p>
Click on the <strong>input rec</strong> button <img src="{{ url('img/input-recording-button.png') }}" alt="Input rec button" title="Input rec button" class="inline" /> or press <span class="code">end</span> to enable the sampler; the new sample will be placed in the first available <strong>sample channel</strong>, and the corresponding status will turn blue. The master play will start automatically, since recording a sound doesn't make sense with the master play turned off. The sampler works in <em>overdub mode</em> by default: the messages coming from the soundcard are being	continuously summed to the existing data until the sampler is halted.
</p>
