
<h1>The FX stack</h1>

<p>
Giada provides VST plugin host functionalities since version 0.4.8; both VST and VSTi (instrument) plugins are supported. The implementation of the VST protocol goes on steadily, but your plugin could malfunction or not work at all! Please report any irregularity into our <a href="{{ url('/forum') }}">forum</a> or via <a href="https://github.com/monocasual/giada">GitHub</a> (for developers).
</p>


<h2>The VST window</h2>
<p>
<img src="{{ url('img/fx-button.png') }}" alt="FX button" title="FX button" class="first" /> The magic button shown on the left opens the list of the VST plugins. This is the window in which you load new plugins, delete the unwanted ones, mute them and tweak the parameters. Wherever it is placed, when clicked it opens the VST window.</p>

<p><img src="{{ url('img/vst-window.png') }}" alt="The VST window" title="The VST window" class="first" /></p>
<p>
Each line corresponds to a plugin. Click on the <strong>name of the effect</strong> to open the plugin window (see below). The menu on the right lists the <strong>presets</strong> (also known as <em>programs</em>). The <strong>check button</strong> <img src="{{ url('img/vst-window-check-button.png') }}" alt="Check button" title="Check button" class="inline" /> enables or disables the plugin while the <strong>up/down buttons</strong> <img src="{{ url('img/vst-window-up-down-buttons.png') }}" alt="Up/down buttons" title="Up/down buttons" class="inline" /> shift the plugin inside the stack. Finally the <strong>remove button</strong> <img src="{{ url('img/vst-window-remove-button.png') }}" alt="Remove button" title="Remove button" class="inline" /> takes away the plugin from the stack.
Add a new plugin by clicking on the button at the end of the stack (<strong>add new plugin</strong>).
</p>

<p>You can load an unlimited number of VST plugins inside Giada; just be aware that they can stress your CPU, compromising the live performance.
</p>

<h2>The plugin window</h2>
<p style="display: inline-block;">By default Giada will try to display the graphical interface of the plugin. In case the plugin doesn't provide an editor <img src="{{ url('img/vst-plugin-window.png') }}" alt="The VST plugin window" title="The VST plugin window" class="first" />, another window will show a list of the parameters, tweakable through the horizontal sliders.</p>

<div class="clearfix"></div>

<h2>VST compatibility</h2>
<p>
VST plugins must be hosted in compatible environments which means, for example, that an OSX plugin cannot be loaded	in the Windows version	of Giada and vice versa.
</p>
