
<div class="row margin-top-m">
	<div class="col-md-6">
		<ol>
		<li><h2><a href="{{ url('documentation/show/introduction') }}">Introduction, installation and first run</a></h2></li>
		<li><h2><a href="{{ url('documentation/show/requirements') }}">Requirements</a></h2><span class="dida">What you need to run Giada</span></li>
		<li><h2><a href="{{ url('documentation/show/compiling-from-source') }}">Compiling from source</a></h2></li>
		<li><h2><a href="{{ url('documentation/show/look-at-the-main-window') }}">A look at the main window</a></h2><span class="dida">How to interact with</span></li>
		<li><h2><a href="{{ url('documentation/show/performing-1') }}">Performing part 1</a></h2><span class="dida">What can I do with Giada?</span></li>
		<li><h2><a href="{{ url('documentation/show/performing-2') }}">Performing part 2</a></h2><span class="dida">Understanding channels and sequencer, keyboard interactions</span></li>
		<li><h2><a href="{{ url('documentation/show/channels-and-samples') }}">Channels and samples</a></h2></li>
		<li><h2><a href="{{ url('documentation/show/channels-and-midi') }}">Channels and MIDI</a></h2></li>
		<li><h2><a href="{{ url('documentation/show/recording-actions') }}">Recording actions</a></h2><span class="dida">How to store your performances</span></li>
		</ol>
	</div>

	<div class="col-md-6">
		<ol start="10">
		<li>
			<h2><a href="{{ url('documentation/show/live-sampling') }}">Live sampling</a></h2>
			<span class="dida">How to store your performances, episode II</span>
		</li>
		<li>
			<h2><a href="{{ url('documentation/show/action-editor') }}">The action editor</a></h2>
			<span class="dida">Fine recording tuning</span>
		</li>
		<li>
			<h2><a href="{{ url('documentation/show/sample-editor') }}">The sample editor</a></h2>
			<span class="dida">Fine sound tuning</span>
		</li>
		<li>
			<h2><a href="{{ url('documentation/show/fx-stack') }}">The FX stack</a></h2>
		</li>
		<li>
			<h2><a href="{{ url('documentation/show/midi-input-management') }}">MIDI input management</a></h2>
		</li>
		<li>
			<h2><a href="{{ url('documentation/show/midi-output-management') }}">MIDI output management</a></h2>
		</li>
		<li>
			<h2><a href="{{ url('documentation/show/save-load-export') }}">Save, load, export</a></h2>
			<span class="dida">Save your works, other interesting options</span>
		</li>
		<li>
			<h2><a href="{{ url('documentation/show/configuration') }}">Configuration</a></h2>
			<span class="dida">Setting up Giada</span>
		</li>
		<li>
			<h2><a href="{{ url('documentation/show/development-git-setup') }}">Development - Git setup</a></h2>
			<span class="dida">Developers, let's join us!</span>
		</li>
		</ol>
	</div>
</div>
