
<h1>Introduction, installation and first run</h1>

<p> {{ config.metas.description }} </p>

<h2>Warnings</h2>
<p>
Giada is in a constant stage of development and may lack of some functionalities which could make it hard to use. Please see the changelog file inside the package	to understand	the direction of development. Giada is obviously full of bugs, too. So please join our <a href="{{ url('forum') }}">forum</a> and submit any malfunction or suggestion.
</p>

<p>
If you are a coder / programmer / developer / hacker and you want to collaborate with the project, join us on <a href="https://github.com/monocasual/giada">GitHub</a>. More informations on the <a href="{{ url('documentation/show/development-git-setup') }}">Git setup</a> page.
</p>


<h2>How to run Giada</h2>
<p>
Go to the <a href="{{ url('download') }}">Download</a> area, grab the package for your operating system, unzip/untar it. Now double-click on the program icon to start Giada. No installation or setup needed.
</p>

<p>
If you are on Linux and you have installed Giada through your package manager, you should find a shortcut in your main menu.
</p>


<h2>The configuration file</h2>
<p>
Giada saves its configuration inside a file called <span class="code">giada.conf</span>, generated somewhere in your filesystem:
</p>
<ul>
	<li>Linux — <span class="code">/home/[your_user]/.giada/giada.conf</span>;</li>
	<li>Mac — <span class="code">[your_home]/Library/Application Support/Giada/giada.conf</span>;</li>
	<li>Windows — in the same folder of the binary file.</li>
</ul>
<p>
If you accidentally delete or alter it, the default setup will be used. This file is restored the next
time you quit the program.
</p>

