
<h1>Live sampling</h1>

<p>Giada gives you the ability to record anything coming in from your soundcard thanks to its live sampler and the master input channel. Configure your device in the <a href="{{ url('documentation/show/configuration') }}">Configuration panel</a> first, then turn up the knob of the <strong>input volume</strong> <img src="{{ url('img/docs/gui_inputmeter.png') }}" alt="The input peakmeter" title="The input peakmeter" class="inline" /> in the main window.</p>

<!--
<p>
The button between the input and the output meter is the <strong>stream linker</strong> <img src="{{ url('img/docs/input-output-linker.png') }}" alt="Input to output linker" title="Input to output linker" class="inline" />: enable it and you will be able to hear what you're playing. Finally you can process the incoming signal by adding some effects on the input side, with the <strong>FX button</strong> <img src="{{ url('img/docs/fx-button.png') }}" alt="FX button" title="FX button" class="inline" />: more informations in the section <a href="{{ url('documentation/show/fx-stack') }}">The FX stack</a>.</p>
-->

<h2>How to use the live sampler</h2>

<p>
First of all you need to add at least one <strong>sample channel</strong>, then arm it with the channel's <strong>arm button</strong> <img src="{{ url('img/docs/arm-button.png') }}" alt="Arm button" title="Arm button" class="inline" />. You can of course arm multiple channels. When you are ready, click on the <strong>input rec</strong> button <img src="{{ url('img/docs/input-recording-button.png') }}" alt="Input rec button" title="Input rec button" class="inline" /> on the main transport or press <span class="code">end</span> to enable the sampler: channels with active input will turn blue.</p>

<p>The master play will start automatically, since recording a sound doesn't make sense with the master play turned off. The sampler works in <em>overdub mode</em> by default: the messages coming from the soundcard are being	continuously summed to the existing data until the sampler is halted.</p>

<h2>Live FX processor</h2>

<p>
The arm button on each sample channel enables the <strong>input monitor</strong>. This way you hear what you're actually playing, previously processed by the plugins stack (if any). If you don't enable the sampler (<strong>input rec</strong> button <img src="{{ url('img/docs/input-recording-button.png') }}" alt="Input rec button" title="Input rec button" class="inline" /> or <span class="code">end</span>), Giada won't record anything and turns into a live FX processor instead.</p>

<p>You can accomplish the same result by using the <strong>stream linker</strong>, the button between the input and the output meter <img src="{{ url('img/docs/input-output-linker.png') }}" alt="Input to output linker" title="Input to output linker" class="inline" />. Enable it and you will be able to hear what you're playing.</p>
