
<h1>A look at the main window</h1>

<p>
After the startup, you should see the main window where all buttons and	levers are grouped. Horizontal lines are channels which contain samples or MIDI events, stacked up in columns. Don't worry if you don't understand the behavior of these tools right now; they will be covered more clearly in the <a href="{{ url('documentation/show/performing-1') }}">Performing 1</a>, <a href="{{ url('documentation/show/performing-2') }}">Performing 2</a>, <a href="{{ url('documentation/show/channels-and-samples') }}">Channels and samples</a> and <a href="{{ url('documentation/show/channels-and-midi') }}">Channels and MIDI</a> sections.
</p>


<h2>Input and output stuff</h2>

<p>
<img src="{{ url('img/docs/gui_peakmeter.png') }}" alt="The output peakmeter" title="The output peakmeter" class="first" /> This is the <strong>output peak meter</strong>. It goes from -60 to 0 dBFS; when the bar is completely full it means that your program is playing at the maximum range available. If you exceed this limit your sound starts to clip and the meter turns to red. The circular knob controls the master volume.
</p>

<p>
<img src="{{ url('img/docs/gui_inputmeter.png') }}" alt="The input peakmeter" title="The input peakmeter" class="first" /> This is the <strong>input peak meter</strong>. It works exactly as the input meter but it manages the sound level coming from the soundcard. Turn the knob to zero in order to mute the recorder.
</p>

<p>
<img src="{{ url('img/docs/input-output-linker.png') }}" alt="Input to output linker" title="Input to output linker" class="first" /> The button between the input and the output meter is a <strong>stream linker</strong>. If enabled, it takes the processed input and it copies it straight onto the output channel, in order to obtain a "hear what you're playing" functionality.
</p>


<h2>The sequencer</h2>

<p>
<img src="{{ url('img/docs/gui_beat.png') }}" alt="The sequencer (or beat bar)" title="The sequencer (or beat bar)" class="first" />
<img src="{{ url('img/docs/gui_playstop.png') }}" alt="Play and stop buttons" title="Play and stop buttons" class="first" /> The <strong>sequencer</strong> shows the current running beat and the total bars of your program. This tool is managed by the two side buttons: <strong>play/stop</strong> and <strong>rewind</strong>. The former simply	starts/stops the beat counting, the latter is used to quickly rewind to the first beat, useful for synching with other audio sources.
</p>



<h2>Recording tools</h2>
<p>
<img src="{{ url('img/docs/gui_recs.png') }}" alt="Recording buttons" title="Recording buttons" class="first" />
These buttons manage the <strong>recordings</strong>. The first one sets Giada to <a href="{{ url('documentation/show/recording-actions') }}">record mode</a>: if switched on, every action (key press, key release, mute on/off, ...) is being stored in memory, then applied to the corresponding channel. The second one starts the <a href="{{ url('documentation/show/live-sampling') }}">live sampler</a>: it records any sound from the sound card input(s) and puts it in the first available channel. Finally the <strong>metronome</strong> <img src="{{ url('img/docs/metronome.png') }}" alt="Metronome" title="Metronome" class="inline" /> might help you during a recording session.
</p>



<h2>Beats, bars, quantizer and BPM</h2>
<p>
<img src="{{ url('img/docs/beats-tools.png') }}" alt="Beats tools" title="Beats tools" class="first" /> A set of tools dedicated to the beat management. You can find them grouped in the top right area of the main window.
</p>
<ul>
<li>
	<strong>Quantizer</strong> <img src="{{ url('img/docs/quantizer.png') }}" alt="Quantizer" title="Quantizer" class="inline" /> — a useful feature which aligns the samples on beats and on exact fractions of beats (for a detailed explanation look at <a href="http://en.wikipedia.org/wiki/Quantization_%28music%29" target="_blank">Wikipedia - Quantization</a>).	The quantizer provides seven operating methods: off (disabled), 1b, 2b, 3b, 4b, 6b, 8b. It operates only when the main program is running and affects those channels which are in a <a href="{{ url('documentation/show/performing') }}">oneshot mode</a>;
</li>
<li>
	<strong>BPM</strong> <img src="{{ url('img/docs/bpm.png') }}" alt="BPM" title="BPM" class="inline" /> — Changes the BPM (i.e. the speed) of the performance;
</li>
<li>
	<strong>Beats/bars</strong> <img src="{{ url('img/docs/beats-bars.png') }}" alt="Beats/bars" title="Beats/bars" class="inline" /> — Changes the number of beats and bars; the feature was designed to provide a graphical hint for your performance and to activate the <a href="{{ url('documentation/show/performing') }}">loop repeat mode</a>. This tool allows to shrink or expand the recorded actions on the timeline through the checkbox <strong>resize recordings</strong> in the small popup window, as well as manage the sub-beats division;
</li>
<li>
	<strong>Beat operators</strong> <img src="{{ url('img/docs/beat-bar-operators.png') }}" alt="Beat operators" title="Beat operators" class="inline" /> — Dynamically shrink or expand the range of the sequencer (i.e. the total number of beats of your performance).
</li>
</ul>



<h2>Sample Channels</h2>
<p>
	<img src="{{ url('img/docs/sample-channel.png') }}" alt="Channels" title="Channels" />
</p>
<p>
The first type of channel is the  <strong>sample channel</strong>. Each element is composed, from left to right by the following elements:
</p>

<ul>
<li>
	<img src="{{ url('img/docs/play-button.png') }}" alt="Play button" title="Play button" class="inline" /> <strong>Play button</strong> — Starts and stops the channel (if loaded);
</li>
<li>
	<img src="{{ url('img/docs/arm-button.png') }}" alt="Arm button" title="Arm button" class="inline" /> <strong>Arm button</strong> — Arms the channel for recording;
</li>
<li>
	<img src="{{ url('img/docs/status-box.png') }}" alt="Status box" title="Status box" class="inline" /> <strong>Status box</strong> — Reports the playback position of the running sample;
</li>
<li>
	<img src="{{ url('img/docs/sample-button.png') }}" alt="Main button" title="Main button" class="inline" /> <strong>Main button</strong> — Shows the name of the loaded sample and allows many operations on it;
</li>
<li>
	<img src="{{ url('img/docs/mute-button.png') }}" alt="Mute button" title="Mute button" class="inline" /> <strong>Mute button</strong> — Mutes the sample;
</li>
<li>
	<img src="{{ url('img/docs/solo-button.png') }}" alt="Mute button" title="Mute button" class="inline" /> <strong>Solo button</strong> — Puts channel in solo mode;
</li>
<li>
	<img src="{{ url('img/docs/fx-button.png') }}" alt="FX button" title="FX button" class="inline" /> <strong>FX button</strong> — Opens up the <a href="{{ url('documentation/show/fx-stack') }}">FX stack</a>;
</li>
<li>
	<img src="{{ url('img/docs/volume-dial.png') }}" alt="Volume dial" title="Volume dial" class="inline" /> <strong>Volume dial</strong> — Controls the volume of the sample;
</li>
<li>
	<img src="{{ url('img/docs/mode_loopa.png') }}" alt="Mode box" title="Mode box" class="inline" /> <strong>Mode box</strong> — Sets the play mode of the channel.
</li>
</ul>


<h2>MIDI Channels</h2>

<p>
	<img src="{{ url('img/docs/midi-channel.png') }}" alt="MIDI channel" title="MIDI channel" />
</p>
<p>
The second type of channel is the  <strong>MIDI channel</strong>. Each element is composed, from left to right by the following elements:
</p>

<ul>
<li>
	<img src="{{ url('img/docs/play-button.png') }}" alt="Play button" title="Play button" class="inline" /> <strong>Play button</strong> — Starts and stops the channel;
</li>
<li>
	<img src="{{ url('img/docs/arm-button.png') }}" alt="Arm button" title="Arm button" class="inline" /> <strong>Arm button</strong> — Arms the channel for recording;
</li>
<li>
	<img src="{{ url('img/docs/midi-button.png') }}" alt="Main button" title="Main button" class="inline" /> <strong>Main button</strong> — If clicked, opens up a menu with options;
</li>
<li>
	<img src="{{ url('img/docs/mute-button.png') }}" alt="Mute button" title="Mute button" class="inline" /> <strong>Mute button</strong> — Mutes the channel;
</li>
<li>
	<img src="{{ url('img/docs/solo-button.png') }}" alt="Mute button" title="Mute button" class="inline" /> <strong>Solo button</strong> — Puts channel in solo mode;
</li>
<li>
	<img src="{{ url('img/docs/fx-button.png') }}" alt="FX button" title="FX button" class="inline" /> <strong>FX button</strong> — Opens up the <a href="{{ url('documentation/show/fx-stack') }}">FX stack</a>;
</li>
<li>
	<img src="{{ url('img/docs/volume-dial.png') }}" alt="Volume dial" title="Volume dial" class="inline" /> <strong>Volume dial</strong> — Controls the volume of the channel;
</li>
</ul>
