
<h1>Performing part 1</h1>

<p>
As you probably already guessed, Giada is based on the concepts of <strong>channels</strong>. A channel can contain one sample (we call it <strong>sample channel</strong>) or MIDI events (we call it <strong>MIDI channel</strong>) and you manage it through some <strong>actions</strong> and <strong>play modes</strong>.</p>

<p>An <strong>action</strong> could be the pressure of a key, the switch of the mute button and so on. Almost all of them can be recorded during the <a href="{{ url('documentation/show/recording-actions') }}">action recording</a> process or manually crafted in the <a href="{{ url('documentation/show/action-editor') }}">action editor</a>. <strong>Play modes</strong> are basically two: <strong>loop</strong> or <strong>one shot</strong> and they define the nature of <strong>sample channels</strong>.
</p>

<p>Play modes, behaviors and statuses for each type of channel will be covered thoroughly in <a href="{{ url('documentation/show/channels-and-samples') }}">Channels and samples</a> and <a href="{{ url('documentation/show/channels-and-midi') }}">Channels and MIDI</a> sections.</p>

<h2>Lots of ways of understanding Giada</h2>

<p>Giada gives you the chance to play in several ways, described below.</p>
<ul>
<li>
	<strong>Giada as a sample player</strong> — channels start to play immediately as their corresponding key is pressed. No further actions are performed. This mode is designed to work in parallel with another stream (e.g. a DJ set);
</li>
<li>
	<strong>Giada loop machine!</strong> — each channel contains an element of the song: channel 1 stores drums, channel 2 stores pads, channel 3 stores leads and so on. While the sequencer is running, you launch and stop those channels. You can also overlay effects and other sounds by playing the remaining channels as you would do in the previous method. The quantizer helps you to align those samples to the grid and if you enable the <a href="{{ url('documentation/show/recording-actions') }}">action recorder</a> you can automate a lot of things;
</li>
<li>
	<strong>Giada as a song editor</strong> — load up your samples or pick up some virtual instruments (synths, drum machines, ...), then open the <a href="{{ url('documentation/show/action-editor') }}">action editor</a> in which you <em>draw</em> the actions manually, as you would do in any other DAW or pattern editor out there. Then you can play those channels in any of the ways seen before;
</li>
<li>
	<strong>Giada as a live sampler</strong> — instead of loading samples from disk, record them from the real world! Those sounds become regular samples that you can use in any of the ways previously discussed.
</li>
<li>
	<strong>Giada as an FX processor</strong> — load as many plugins as you wish in the input channel and link it to the output; Giada will process the FXs in realtime, outputting the result directly in your speakers.
</li>
</ul>

<p>Of course all of the previous modes can be combined together, according to your style and liking.</p>
