
<h1>Recording actions</h1>

<p>You know that an <strong>action</strong> is basically something you do on a channel.	Before doing anything, Giada must be put in <em>record mode</em>. You can do this by	clicking on the <strong>action rec button</strong> <img src="{{ url('img/docs/action-recorder-button.png') }}" alt="Action recorder button" title="Action recorder button" class="inline" /> or by pressing the <span class="code">enter</span> key: all the recordable channels will turn red.<p>

<p>Then start your performance, be it via computer keyboard or a MIDI device. When you're done, disable the record mode by clicking on the <strong>action rec button</strong> a second time: you will notice that all the channels with something recorded show a "R" button <img src="{{ url('img/docs/read-recs-button.png') }}" alt="Read recordings button" title="Read recordings button" class="inline" />: this one enables or disables the recordings.</p>

<p>If you need to erase the actions on a channel, click on the sample button and select <em>clear recordings</em>, or tweak them more thoroughly with the <a href="{{ url('documentation/show/action-editor') }}">action editor</a>.
</p>

<h2>What types of action can I record?</h2>

<p>For the time being, on a <strong>sample channel</strong> you can record the following types:</p>
<ul>
<li>key press;</li>
<li>key release;</li>
<li>sample kill;</li>
<li>channel mute.</li>
</ul>

<p>On a <strong>MIDI channel</strong> you can't do anything live, for now.</p>
