
<h1>Recording actions</h1>

<p>You know that an <strong>action</strong> is basically something you do on a channel.	Before doing anything, Giada must be put in <em>record mode</em>. You can do that by clicking on the <strong>action rec button</strong> <img src="{{ url('img/docs/action-recorder-button.png') }}" alt="Action recorder button" title="Action recorder button" class="inline" /> or by pressing the <span class="code">enter</span> key: now Giada will record any action coming from your mouse+keyboard and/or MIDI controllers.<p>

<h2>Actions for sample channels</h2>

<p>On a <strong>sample channel</strong> you can record the following types:</p>
<ul>
<li>key press;</li>
<li>key release;</li>
<li>sample kill;</li>
<li>channel mute.</li>
</ul>

<p>Start your performance, be it via computer keyboard or a MIDI device. Sample channels available and ready for recording will turn red. When you're done, disable the record mode by clicking on the <strong>action rec button</strong> a second time: you will notice that all the sample channels with something recorded show a "R" button <img src="{{ url('img/docs/read-recs-button.png') }}" alt="Read recordings button" title="Read recordings button" class="inline" />: this one enables or disables the recordings.</p>

<p>If you need to erase the actions on a sample channel, click on the sample button and select <em>clear recordings</em>, or tweak them more thoroughly with the <a href="{{ url('documentation/show/action-editor') }}">action editor</a>.
</p>

<h2>Actions for MIDI channels</h2>

<p>
On <strong>MIDI channels</strong> you can record any type of MIDI event supported by the <a href="{{ url('documentation/show/action-editor') }}">piano roll editor</a>. First of all press the <strong>arm button</strong> <img src="{{ url('img/docs/arm-button.png') }}" alt="Arm button" title="Arm button" class="inline" />, then start your performance with your MIDI controller. When you're done, disable the record mode by clicking on the <strong>action rec button</strong> a second time.
</p>

<p>If you need to erase the actions on a MIDI channel, click on the sample button and select <em>clear recordings</em>, or tweak them more thoroughly with the <a href="{{ url('documentation/show/action-editor') }}">action editor</a>.

<h3>Live FX processor</h3>

<p>You can also arm one or more MIDI channels without tiggering the main recorder. This way Giada turns into a live FX processor, driven by your MIDI notes in input. This is very useful when you want to live play your virtual instruments through a MIDI controller.</p>
