
<h1>Requirements</h1>

<p>
Giada is based upon the following libraries:</p>
<ul>
<li><a href="http://www.music.mcgill.ca/~gary/rtaudio/" title="RtAudio">RtAudio</a>;</li>
<li><a href="http://www.music.mcgill.ca/~gary/rtmidi/" title="RtMidi">RtMidi</a>;</li>
<li><a href="http://www.fltk.org/" title="FLTK GUI Toolkit">FLTK</a> (GUI);</li>
<li><a href="http://www.digip.org/jansson/" title="Jansson">Jansson</a>;</li>
<li><a href="http://www.mega-nerd.com/libsndfile/" title="Libsndfile">Libsndfile</a>;</li>
<li><a href="http://www.mega-nerd.com/SRC/" title="Libsamplerate">Libsamplerate</a>.</li>
</ul>

<p>These libraries are statically linked: everything you need is inside the binary you have downloaded. Nevertheless things get little different whether you are using Windows or Linux version of Giada.
</p>



<h2>Windows</h2>
<p>
You should be able to run Giada without troubles if you keep <span class="code">pthreadGC2.dll</span> in the same directory where <span class="code">giada_win.exe</span> is located. That dll is shipped with the zip package. Supported version: Windows XP or greater.
</p>



<h2>OS X</h2>
<p>
Don't worry about a thing. Supported version: Mac OS X 10.5 or greater.
</p>



<h2>Linux</h2>
<p>
Well, we lied: on Linux <strong>Libsndfile</strong>, <strong>Libsamplerate</strong> and <strong>Jansson</strong> are not statically linked. Moreover Giada relies on <a href="http://www.jackaudio.org" title="Jack Audio">Jack</a> to benefit of its advanced streaming functionalities.	Those should not be a problem thanks to the comfortable <em>deb package</em> for Debian distros, which should take care of the missing dependencies. If you experience any troubles with our package you should also try binaries provided by the package manager of your favorite distribution. Giada is already available on Debian, Ubuntu, Arch Linux and many more.</p>
