
<h1>Requirements</h1>

<p>
Giada is based upon <a href="http://www.music.mcgill.ca/~gary/rtaudio/" title="RtAudio">RtAudio</a>, <a href="http://www.music.mcgill.ca/~gary/rtmidi/" title="RtMidi">RtMidi</a>, 
<a href="http://www.fltk.org/" title="FLTK GUI Toolkit">FLTK</a> (GUI),
<a href="http://www.mega-nerd.com/libsndfile/" title="libsndfile">libsndfile</a> and <a href="http://www.mega-nerd.com/SRC/" title="libsamplerate">libsamplerate</a>. These libraries are statically linked: everything you need is inside the binary you have downloaded. Nevertheless things get little different whether you are using Windows or Linux version of Giada.
</p>



<h2>Windows</h2>
<p>
You should be able to run Giada without troubles if you keep <span class="code">pthreadGC2.dll</span> in the same directory where <span class="code">giada_win.exe</span> is located. That dll is shipped with the zip package. Supported version: Windows XP or greater.
</p>



<h2>OS X</h2>
<p>
Don't worry about a thing. Supported version: Mac OS X 10.5 or greater.
</p>



<h2>Linux</h2>
<p>
Well, we lied: on Linux <a href="http://www.mega-nerd.com/libsndfile/" title="libsndfile">libsndfile</a> and <a href="http://www.mega-nerd.com/SRC/" title="libsamplerate">libsamplerate</a> are not statically linked. Moreover Giada relies on <a href="http://www.jackaudio.org" title="Jack Audio">Jack</a> to benefit of its advanced streaming functionalities.	Those should not be a problem thanks to the comfortable <em>deb package</em> for Debian distros, which should take care of the missing dependencies. If you experience any troubles with that package you may try the "plain" binaries in the download section, but remember that
you still need <span class="code">libjack.so</span>, <span class="code">libsndfile.so</span> and <span class="code">libsamplerate.so</span> to run Giada. If you wish to dig deeper we report the complete <span class="code">ldd</span> command (shared library dependencies) <sup>August 2014, version 0.9.0</sup>:
</p>
<p class="code">
	linux-vdso.so.1 =>  (0x00007fff30bfe000)<br />
	libsndfile.so.1 => /usr/local/lib/libsndfile.so.1 (0x00007f877fc92000)<br />
	libX11.so.6 => /usr/lib/x86_64-linux-gnu/libX11.so.6 (0x00007f877f95d000)<br />
	libXpm.so.4 => /usr/lib/x86_64-linux-gnu/libXpm.so.4 (0x00007f877f74a000)<br />
	libjack.so.0 => /usr/lib/x86_64-linux-gnu/libjack.so.0 (0x00007f877f52d000)<br />
	libasound.so.2 => /usr/lib/x86_64-linux-gnu/libasound.so.2 (0x00007f877f23d000)<br />
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f877f01e000)<br />
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f877ee1a000)<br />
	libpulse-simple.so.0 => /usr/lib/x86_64-linux-gnu/libpulse-simple.so.0 (0x00007f877ec16000)<br />
	libpulse.so.0 => /usr/lib/x86_64-linux-gnu/libpulse.so.0 (0x00007f877e9cc000)<br />
	libsamplerate.so.0 => /usr/local/lib/libsamplerate.so.0 (0x00007f877e660000)<br />
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f877e35c000)<br />
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f877e055000)<br />
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f877de3f000)<br />
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f877da79000)<br />
	libxcb.so.1 => /usr/lib/x86_64-linux-gnu/libxcb.so.1 (0x00007f877d859000)<br />
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f877d651000)<br />
	/lib64/ld-linux-x86-64.so.2 (0x00007f877ff0c000)<br />
	libpulsecommon-4.0.so => /usr/lib/x86_64-linux-gnu/pulseaudio/libpulsecommon-4.0.so (0x00007f877d3e9000)<br />
	libjson-c.so.2 => /lib/x86_64-linux-gnu/libjson-c.so.2 (0x00007f877d1de000)<br />
	libdbus-1.so.3 => /lib/x86_64-linux-gnu/libdbus-1.so.3 (0x00007f877cf99000)<br />
	libXau.so.6 => /usr/lib/x86_64-linux-gnu/libXau.so.6 (0x00007f877cd94000)<br />
	libXdmcp.so.6 => /usr/lib/x86_64-linux-gnu/libXdmcp.so.6 (0x00007f877cb8e000)<br />
	libwrap.so.0 => /lib/x86_64-linux-gnu/libwrap.so.0 (0x00007f877c983000)<br />
	libasyncns.so.0 => /usr/lib/x86_64-linux-gnu/libasyncns.so.0 (0x00007f877c77d000)<br />
	libnsl.so.1 => /lib/x86_64-linux-gnu/libnsl.so.1 (0x00007f877c562000)<br />
	libresolv.so.2 => /lib/x86_64-linux-gnu/libresolv.so.2 (0x00007f877c347000)
</p>
