
<h1>The Sample Editor</h1>

<p>
<img src="{{ url('img/docs/giada-sample-editor.png') }}" alt="The sample editor" title="The sample editor" class="first" /> Giada is shipped with a powerful sample editor for fine manipulations of your samples. While the main window provides a fast and basic interaction, inside the editor you may tweak several parameters such as start/end points, volume, pitch, boost and much more.
</p>

<p>The Sample Editor also provides some basic tools for cutting, trimming or silencing your sample. Those are destructive actions; if you damage the sample you have to reload it from disk. Don't worry, the damage will occur only in memory; the original file won't be touched!</p>

<p>On the lower right corner of the Sample Editor you will find some additional information on the sample currently loaded, such as the original file path, the size (in audio frames), the duration (in seconds), the bit depth and the frequency.</p>

<div class="clearfix"></div>

<h2>Start/end points</h2>
<p>
Start/end points are used to set the play range of the sample and are represented by two
vertical lines with a square handle: click on that handle and drag it around to set the points quickly, or use the boxes below the waveform for a precise, numeric setup. The <strong>Reset</strong> button restores the default configuration.
</p>



<h2>Volume and boost</h2>
<p>
The <strong>Volume</strong> knob <img src="{{ url('img/docs/volume-knob.png') }}" alt="Volume knob" title="Volume knob" class="inline" /> reflects the one located on the main window, running from -inf to 0.0 dB. The <strong>Boost</strong>
slider <img src="{{ url('img/docs/boost-knob.png') }}" alt="Boost knob" title="Boost knob" class="inline" /> is used to rise the signal level of a quiet sample; its range goes from 0.0 to 20.0 dB.
</p>



<h2>Normalize</h2>
<p>
The <strong>Normalize</strong> button <img src="{{ url('img/docs/normalize.png') }}" alt="Normalize" title="Normalize" class="inline" /> parses the entire sample and raises its highest peak to 0.0 dB, setting the boost level
accordingly. If the highest peak is greater than 0.0 dB (it could happen with a floating point sample), the function brings it down to 0.0 dB. If the sample is silent, it does nothing.
</p>



<h2>Panning</h2>
<p>
The <strong>Pan</strong> knob <img src="{{ url('img/docs/panning-knob.png') }}" alt="Panning knob" title="Panning knob" class="inline" /> sets the position of the sample into the stereo field. "L" stands for Left, "R" for Right
and "C" for center.
</p>



<h2>Pitch</h2>
<p>
The <strong>Pitch</strong> knob <img src="{{ url('img/docs/pitch-knob.png') }}" alt="Pitch knob" title="Pitch knob" class="inline" /> streches or compresses the sample, making it sound faster or slower. It works exactly as a turntable pitch control slider. It's currently powered by the Linear algorithm from Libsamplerate (very fast, low quality).
</p>
<p>
You can spread the sample accross the whole song or the current bar by pressing <strong>To song</strong> and <strong>To bar</strong> buttons. Two additional operators, <strong>×</strong> and <strong>÷</strong> will double or halve the sample's duration, while the <strong>Reset</strong> button restores the pitch to 1.0.
</p>


<h2>Editing operations</h2>
<p><img src="{{ url('img/docs/sample-editor-popup-menu.png') }}" alt="The editing menu in the sample editor" title="The editing menu in the sample editor" class="first" /></p>
<p>
Select a portion of the waveform with the mouse and click on it with the <em>right button</em>: a menu will appear, giving you some editing tools:
</p>
<ul>
<li><strong>Cut</strong> — removes a portion from the sample and store it to memory. It can be pasted later on;</li>
<li><strong>Copy</strong> — stores the selected range in memory, for later paste;</li>
<li><strong>Paste</strong> — pastes the data stored in memory. This option is available also when you right-click on the waveform with no selection, in order to paste to a specific frame;</li>
<li><strong>Trim</strong> — removes all but the selected portion;</li>
<li><strong>Silence</strong> — mutes the selected portion (sets the amplitude to 0);</li>
<li><strong>Reverse</strong> — flips the data in the selected range;</li>
<li><strong>Normalize</strong> — raises the volume of the selected range to 0.0 dB. Note that, unlike the <em>normalize</em> button described above, this operation modifies the actual data: you have to reload the sample from disk in order to restore it to the original state;</li>
<li><strong>Fade in/Fade out</strong> — applies a linear fade in/out;</li>
<li><strong>Smooth edges</strong> — shapes gracefully the edges of a selection;</li>
<li><strong>Set start/end here</strong> — sets the <em>start</em> / <em>end</em> points to the selection boundaries;</li>
<li><strong>Copy to new channel</strong> — creates a new Sample Channel out of the selection.</li>
</ul>
<p>Did you mess with the sample? You can reload it from disk by clicking on the <strong>Reload</strong> button <img src="{{ url('img/docs/reload-button.png') }}" alt="Reload button" title="Reload button" class="inline" />. </p>
<div class="clearfix"></div>
