
<h1>The Sample Editor</h1>

<p>
<img src="{{ url('img/docs/giada-sample-editor.png') }}" alt="The sample editor" title="The sample editor" class="first" /> Giada 0.3.0 introduced this useful tool for fine manipulations of your samples. While the main window provides a fast and basic interaction, inside the editor you may tweak several parameters such as start points, end points, fine volume, boost and more.
</p>


<p>The editor also provides some basic tools for cutting, trimming or silencing your sample. Those are destructive actions; if you damage the sample you have to reload it from disk. Don't worry, the damage will occur only in memory; the original file won't be touched!</p>

<div class="clearfix"></div>

<h2>Start/end points</h2>
<p>
Start/end points are used to set the play range of the sample and are represented by two
vertical lines labeled "S" (<em>start</em>) <img src="{{ url('img/docs/start-point.png') }}" alt="Start point" title="Start point" class="inline" /> and "E" (<em>end</em>) <img src="{{ url('img/docs/end-point.png') }}" alt="End point" title="End point" class="inline" />: click on each label and drag it around to
set the points quickly, or use the boxes below for a precise, numeric setup. The <strong>Reset</strong> button
restore the default configuration.
</p>



<h2>Volume and boost</h2>
<p>
The <strong>Volume</strong> knob <img src="{{ url('img/docs/volume-knob.png') }}" alt="Volume knob" title="Volume knob" class="inline" /> reflects the one located on the main window, running from -inf to 0.0 dB. The <strong>Boost</strong>
slider <img src="{{ url('img/docs/boost-knob.png') }}" alt="Boost knob" title="Boost knob" class="inline" /> is used to rise the signal level of a quiet sample; its range goes from 0.0 to 20.0 dB.
</p>



<h2>Normalize</h2>
<p>
The <strong>Normalize</strong> button <img src="{{ url('img/docs/normalize.png') }}" alt="Normalize" title="Normalize" class="inline" /> parses the entire sample and brings its highest peak to 0.0 dB, setting the boost level
accordingly. If the highest peak is greater than 0.0 dB (it could happen with a floating point sample), the function brings it down to 0.0 dB. If the sample is silent, it does nothing.
</p>



<h2>Panning</h2>
<p>
The <strong>Pan</strong> knob <img src="{{ url('img/docs/panning-knob.png') }}" alt="Panning knob" title="Panning knob" class="inline" /> sets the position of the sampled sound into the stereo field. "L" stands for Left, "R" for Right
and "C" for center.
</p>



<h2>Pitch</h2>
<p>
The <strong>Pitch</strong> knob <img src="{{ url('img/docs/pitch-knob.png') }}" alt="Pitch knob" title="Pitch knob" class="inline" /> streches or compresses the sample, making it sound faster or slower. It works exactly as a turntable pitch control slider. It's powered by the Linear algorithm from Libsamplerate (very fast, low quality).
</p>



<h2>Cut, trim, silence, ...</h2>
<p><img src="{{ url('img/docs/sample-editor-popup-menu.png') }}" alt="The editing menu in the sample editor" title="The editing menu in the sample editor" class="first" /></p>
<p>
Select a portion of the waveform with the mouse and click on it with the <em>right button</em>: a menu will appear, giving you some editing tools:
</p>
<ul>
<li><strong>Cut</strong> — removes a portion from the sample;</li>
<li><strong>Trim</strong> — removes all but the selected portion;</li>
<li><strong>Silence</strong> — mutes the selected portion (set the amplitude to 0);</li>
<li><strong>Fade in/Fade out</strong> — applies a linear fade in/out;</li>
<li><strong>Smooth edges</strong> — shapes gracefully the edges of a selection;</li>
<li><strong>Set start/end here</strong> — sets the <em>start</em> / <em>end</em> points to the selection boundaries.</li>
</ul>
<p>Did you mess with the sample? You can reload it from disk by clicking on the <strong>Reload</strong> button <img src="{{ url('img/docs/reload-button.png') }}" alt="Reload button" title="Reload button" class="inline" />. </p>
<div class="clearfix"></div>
