<ol>
<li><a href="{{ url('documentation') }}">Index</a></li>
<li><a href="{{ url('documentation/show/introduction') }}">Introduction, installation and first run</a></li>
<li><a href="{{ url('documentation/show/requirements') }}">Requirements</a></li>
<li><a href="{{ url('documentation/show/compiling-from-source') }}">Compiling from source</a></li>
<li><a href="{{ url('documentation/show/look-at-the-main-window') }}">A look at the main window</a></li>
<li><a href="{{ url('documentation/show/performing-1') }}">Performing part 1</a></li>
<li><a href="{{ url('documentation/show/performing-2') }}">Performing part 2</a></li>
<li><a href="{{ url('documentation/show/channels-and-samples') }}">Channels and samples</a></li>
<li><a href="{{ url('documentation/show/channels-and-midi') }}">Channels and MIDI</a></li>
<li><a href="{{ url('documentation/show/recording-actions') }}">Recording actions</a></li>
<li><a href="{{ url('documentation/show/live-sampling') }}">Live sampling</a></li>
<li><a href="{{ url('documentation/show/action-editor') }}">The action editor</a></li>
<li><a href="{{ url('documentation/show/sample-editor') }}">The sample editor</a></li>
<li><a href="{{ url('documentation/show/fx-stack') }}">The FX stack</a></li>
<li><a href="{{ url('documentation/show/midi-input-management') }}">MIDI input management</a></li>
<li><a href="{{ url('documentation/show/midi-output-management') }}">MIDI output management</a></li>
<li><a href="{{ url('documentation/show/save-load-export') }}">Save, load, export</a></li>
<li><a href="{{ url('documentation/show/configuration') }}">Configuration</a></li>
<li><a href="{{ url('documentation/show/development-git-setup') }}">Development - Git setup</a></li>
</ol>
